CategoryGenre.create([
  { name: "レディース" },
  { name: "メンズ" },
  { name: "ベビー・キッズ" },
  { name: "インテリア・住まい" },
  { name: "本・音楽・ゲーム" },
  { name: "おもちゃ・ホビー" },
  { name: "コスメ・香水・美容" },
  { name: "家電・スマホ・カメラ" },
  { name: "スポーツ・レジャー" },
  { name: "ハンドメイド" },
  { name: "チケット" },
  { name: "自転車・オートバイ" },
  { name: "その他" },
  ])

Category.create([
  {category_genre_id: 1, name: "トップス"},
  {category_genre_id: 1, name: "ジャケット/アウター"},
  {category_genre_id: 1, name: "パンツ"},
  {category_genre_id: 1, name: "スカート"},
  {category_genre_id: 1, name: "ワンピース"},
  {category_genre_id: 1, name: "靴"},
  {category_genre_id: 1, name: "ルームウェア"},
  {category_genre_id: 1, name: "レッグウェア"},
  {category_genre_id: 1, name: "帽子"},
  {category_genre_id: 1, name: "アクセサリー"},
  {category_genre_id: 1, name: "ヘアアクセサリー"},
  {category_genre_id: 1, name: "小物"},
  {category_genre_id: 1, name: "時計"},
  {category_genre_id: 1, name: "ウィッグ/エクステ"},
  {category_genre_id: 1, name: "浴衣/水着"},
  {category_genre_id: 1, name: "スーツ"},
  {category_genre_id: 1, name: "フォーマル"},
  {category_genre_id: 1, name: "ドレス"},
  {category_genre_id: 1, name: "マタニティ"},
  {category_genre_id: 1, name: "その他"},
  ])


Category.create([
  {category_genre_id: 2, name: "トップス"},
  {category_genre_id: 2, name: "ジャケット/アウター"},
  {category_genre_id: 2, name: "パンツ"},
  {category_genre_id: 2, name: "靴"},
  {category_genre_id: 2, name: "バック"},
  {category_genre_id: 2, name: "スーツ"},
  {category_genre_id: 2, name: "帽子"},
  {category_genre_id: 2, name: "アクセサリー"},
  {category_genre_id: 2, name: "小物"},
  {category_genre_id: 2, name: "時計"},
  {category_genre_id: 2, name: "レッグウェア"},
  {category_genre_id: 2, name: "アンダーウェア"},
  {category_genre_id: 2, name: "スポーツ"},
  {category_genre_id: 2, name: "ウィッグ"},
  {category_genre_id: 2, name: "浴衣"},
  {category_genre_id: 2, name: "カジュアル"},
  {category_genre_id: 2, name: "フォーマル"},
  {category_genre_id: 2, name: "ルームウェア"},
  {category_genre_id: 2, name: "ビジネス"},
  {category_genre_id: 2, name: "その他"},
  ])
Category.create([
  {category_genre_id: 3, name: "キッズ靴"},
  {category_genre_id: 3, name: "ベビー服(女の子用) ~95cm"},
  {category_genre_id: 3, name: "ベビー服(男の子用) ~95cm"},
  {category_genre_id: 3, name: "ベビー服(男女兼用) ~95cm"},
  {category_genre_id: 3, name: "キッズ服(女の子用) 100cm~"},
  {category_genre_id: 3, name: "キッズ服(男の子用) 100cm~"},
  {category_genre_id: 3, name: "キッズ服(男女兼用) 100cm~"},
  {category_genre_id: 3, name: "子ども用ファッション小物"},
  {category_genre_id: 3, name: "おむつ/トイレ/バス"},
  {category_genre_id: 3, name: "トイレ/バス"},
  {category_genre_id: 3, name: "外出/移動用品"},
  {category_genre_id: 3, name: "授乳/食事"},
  {category_genre_id: 3, name: "ベビー家具"},
  {category_genre_id: 3, name: "寝具"},
  {category_genre_id: 3, name: "おもちゃ"},
  {category_genre_id: 3, name: "行事/記念品"},
  {category_genre_id: 3, name: "フォーマル"},
  {category_genre_id: 3, name: "ルームウェア"},
  {category_genre_id: 3, name: "室内用品"},
  {category_genre_id: 3, name: "その他"},
  ])
Category.create([
  {category_genre_id: 4, name: "収納家具"},
  {category_genre_id: 4, name: "椅子/チェア"},
  {category_genre_id: 4, name: "ソファ"},
  {category_genre_id: 4, name: "キッチン"},
  {category_genre_id: 4, name: "食器"},
  {category_genre_id: 4, name: "ベッド"},
  {category_genre_id: 4, name: "マットレス"},
  {category_genre_id: 4, name: "ソファベッド"},
  {category_genre_id: 4, name: "机/テーブル"},
  {category_genre_id: 4, name: "ラグ"},
  {category_genre_id: 4, name: "カーペット/マット"},
  {category_genre_id: 4, name: "カーテン"},
  {category_genre_id: 4, name: "ライト/照明"},
  {category_genre_id: 4, name: "寝具"},
  {category_genre_id: 4, name: "インテリア小物"},
  {category_genre_id: 4, name: "季節"},
  {category_genre_id: 4, name: "年中行事"},
  {category_genre_id: 4, name: "ブラインド"},
  {category_genre_id: 4, name: "テーブル"},
  {category_genre_id: 4, name: "その他"},
  ])
Category.create([
  {category_genre_id: 5, name: "CD"},
  {category_genre_id: 5, name: "本"},
  {category_genre_id: 5, name: "テレビゲーム"},
  {category_genre_id: 5, name: "DVD/ブルーレイ"},
  {category_genre_id: 5, name: "雑誌"},
  {category_genre_id: 5, name: "漫画"},
  {category_genre_id: 5, name: "レコード"},
  {category_genre_id: 5, name: "LP"},
  {category_genre_id: 5, name: "カードゲーム"},
  {category_genre_id: 5, name: "TRPG"},
  {category_genre_id: 5, name: "ミニチュアゲーム"},
  {category_genre_id: 5, name: "ボードゲーム"},
  {category_genre_id: 5, name: "カードゲーム"},
  {category_genre_id: 5, name: "ドミノ"},
  {category_genre_id: 5, name: "ダイスゲーム"},
  {category_genre_id: 5, name: "麻雀"},
  {category_genre_id: 5, name: "筐体"},
  {category_genre_id: 5, name: "ビデオ"},
  {category_genre_id: 5, name: "フィルム"},
  {category_genre_id: 5, name: "その他"},
  ])

Category.create([
  {category_genre_id: 6, name: "おもちゃ"},
  {category_genre_id: 6, name: "タレントグッズ"},
  {category_genre_id: 6, name: "コミック/アニメグッズ"},
  {category_genre_id: 6, name: "浮世絵"},
  {category_genre_id: 6, name: "フィギュア"},
  {category_genre_id: 6, name: "楽器/器材"},
  {category_genre_id: 6, name: "コレクション"},
  {category_genre_id: 6, name: "ミリタリー"},
  {category_genre_id: 6, name: "陶芸"},
  {category_genre_id: 6, name: "ガラス"},
  {category_genre_id: 6, name: "漆芸"},
  {category_genre_id: 6, name: "金属工芸"},
  {category_genre_id: 6, name: "絵画/タペストリ"},
  {category_genre_id: 6, name: "トレーディングカード"},
  {category_genre_id: 6, name: "版画"},
  {category_genre_id: 6, name: "彫刻/オブジェクト"},
  {category_genre_id: 6, name: "書"},
  {category_genre_id: 6, name: "写真"},
  {category_genre_id: 6, name: "アート用品"},
  {category_genre_id: 6, name: "その他"},
  ])

Category.create([
  { category_genre_id: 7, name: "ベースメイク"},
  { category_genre_id: 7, name: "メイクアップ"},
  { category_genre_id: 7, name: "ネイルカラー"},
  { category_genre_id: 7, name: "香水（女性用）"},
  { category_genre_id: 7, name: "香水（男性用）"},
  { category_genre_id: 7, name: "ネイルアート用品"},
  { category_genre_id: 7, name: "ネイルパーツ"},
  { category_genre_id: 7, name: "ネイルチップ/付け爪"},
  { category_genre_id: 7, name: "美顔用品/美顔ローラー"},
  { category_genre_id: 7, name: "フットケア"},
  { category_genre_id: 7, name: "芳香器"},
  { category_genre_id: 7, name: "メイク道具/化粧小物"},
  { category_genre_id: 7, name: "基礎化粧品"},
  { category_genre_id: 7, name: "スキンケア"},
  { category_genre_id: 7, name: "ヘアケア"},
  { category_genre_id: 7, name: "ボディケア"},
  { category_genre_id: 7, name: "オーラルケア"},
  { category_genre_id: 7, name: "リラクゼーション"},
  { category_genre_id: 7, name: "ダイエット"},
  { category_genre_id: 7, name: "その他"},
  ])






141.upto(160) do |i|
  Category.create( name: "家電#{i}", category_genre_id: 8)
end
161.upto(180) do |i|
  Category.create( name: "スポーツ#{i}", category_genre_id: 9)
end
181.upto(200) do |i|
  Category.create( name: "ハンドメイド#{i}", category_genre_id: 10)
end
201.upto(220) do |i|
  Category.create( name: "チケット#{i}", category_genre_id: 11)
end
221.upto(240) do |i|
  Category.create( name: "自動車#{i}", category_genre_id: 12)
end
241.upto(260) do |i|
  Category.create( name: "その他#{i}", category_genre_id: 13)
end


BrandGenre.create([
  { name: "レディース" },
  { name: "メンズ" },
  { name: "ベビー・キッズ" },
  { name: "インテリア・住まい" },
  { name: "キッチン・食器" },
  { name: "時計" },
  { name: "コスメ・香水・美容" },
  { name: "テレビゲーム" },
  { name: "スポーツ・レジャー" },
  { name: "スマートフォン" },
  { name: "バイク" },
  { name: "楽器" },
  { name: "自動車" },
  { name: "食品" },
  ])

Brand.create([
  { brand_genre_id: 1, name: "ルイヴィトン" },
  { brand_genre_id: 1, name: "シャネル" },
  { brand_genre_id: 1, name: "アーバンリサーチ" },
  { brand_genre_id: 1, name: "フェンディ" },
  { brand_genre_id: 1, name: "TADASHI SHOJI" },
  { brand_genre_id: 1, name: "メゾンフルール" },
  { brand_genre_id: 1, name: "ヴゼット" },
  { brand_genre_id: 1, name: "ユニクロ" },
  { brand_genre_id: 1, name: "YVESANTLAURENT(イブサンローラン)" },
  { brand_genre_id: 1, name: "GAP" },
  { brand_genre_id: 1, name: "NIKE" },
  { brand_genre_id: 1, name: "サルヴァトーレフェラガモ" },
  { brand_genre_id: 1, name: "BOSCH(ボッシュ)" },
  { brand_genre_id: 1, name: "aquagirl" },
  { brand_genre_id: 1, name: "バレンシアガ" },
  { brand_genre_id: 1, name: "伊太利屋" },
  { brand_genre_id: 1, name: "ワコール" },
  { brand_genre_id: 1, name: "ランバン" },
  { brand_genre_id: 1, name: "HERMES(エルメス)" },
  { brand_genre_id: 1, name: "その他（ノーブランド）" },
  { brand_genre_id: 2, name: "ビームス" },
  { brand_genre_id: 2, name: "RALPHLAUREN" },
  { brand_genre_id: 2, name: "UNITED ALLOWS" },
  { brand_genre_id: 2, name: "ARMANI" },
  { brand_genre_id: 2, name: "DIESEL" },
  { brand_genre_id: 2, name: "しまむら" },
  { brand_genre_id: 2, name: "ZARA" },
  { brand_genre_id: 2, name: "H&M" },
  { brand_genre_id: 2, name: "GAP" },
  { brand_genre_id: 2, name: "GU" },
  { brand_genre_id: 2, name: "SHIPS KIDS" },
  { brand_genre_id: 2, name: "フィス" },
  { brand_genre_id: 2, name: "プチバトー" },
  { brand_genre_id: 2, name: "パンパンチュチュ" },
  { brand_genre_id: 2, name: "ボボショセス" },
  { brand_genre_id: 2, name: "ボンポワン" },
  { brand_genre_id: 2, name: "ミナペルホネン" },
  { brand_genre_id: 2, name: "ククゥマノン" },
  { brand_genre_id: 2, name: "ポロ ラルフ ローレン" },
  { brand_genre_id: 2, name: "ランバン" },
  { brand_genre_id: 3, name: "アルマーニジュニア" },
  { brand_genre_id: 3, name: "ラルフローレン ベビー" },
  { brand_genre_id: 3, name: "ベビー ギャップ" },
  { brand_genre_id: 3, name: "フェンディ" },
  { brand_genre_id: 3, name: "メゾンキツネ" },
  { brand_genre_id: 3, name: "メゾンフルール" },
  { brand_genre_id: 3, name: "ヴゼット" },
  { brand_genre_id: 3, name: "Y3" },
  { brand_genre_id: 3, name: "ロキト" },
  { brand_genre_id: 3, name: "ブラックバイマウジー" },
  { brand_genre_id: 3, name: "ピンキー＆ダイアン" },
  { brand_genre_id: 3, name: "ナラカミーチェ" },
  { brand_genre_id: 3, name: "セタイチロウ" },
  { brand_genre_id: 3, name: "aquagirl" },
  { brand_genre_id: 3, name: "メンズビギ" },
  { brand_genre_id: 3, name: "ガラージュ" },
  { brand_genre_id: 3, name: "ポロ ラルフ ローレン" },
  { brand_genre_id: 3, name: "ランバン" },
  { brand_genre_id: 3, name: "オロビアンコ" },
  { brand_genre_id: 3, name: "ケープハイツ" },
  { brand_genre_id: 4, name: "IDÉE" },
  { brand_genre_id: 4, name: "TRUCK FURNITURE" },
  { brand_genre_id: 4, name: "Eames" },
  { brand_genre_id: 4, name: "Francfranc" },
  { brand_genre_id: 4, name: "STREAMLINE SOFA" },
  { brand_genre_id: 4, name: "CH24" },
  { brand_genre_id: 4, name: "arflex" },
  { brand_genre_id: 4, name: "HUKLA" },
  { brand_genre_id: 4, name: "H.W.F" },
  { brand_genre_id: 4, name: "LENSVELT" },
  { brand_genre_id: 4, name: "HIRASHIMA(" },
  { brand_genre_id: 4, name: "MASTERWAL" },
  { brand_genre_id: 4, name: "カリモク家具" },
  { brand_genre_id: 4, name: "柏木工" },
  { brand_genre_id: 4, name: "maruni" },
  { brand_genre_id: 4, name: "string" },
  { brand_genre_id: 4, name: "PACIFIC FURNITURE SERVICE" },
  { brand_genre_id: 4, name: "ACME FURNITURE" },
  { brand_genre_id: 4, name: "METROCS" },
  { brand_genre_id: 4, name: "広松木工" },
  ])

81.upto(100) do |i|
  Brand.create( name: "キッチン・食器#{i}", brand_genre_id: 5)
end
101.upto(120) do |i|
  Brand.create( name: "時計#{i}", brand_genre_id: 6)
end

Brand.create([
  { brand_genre_id: 7, name: "エルメス" },
  { brand_genre_id: 7, name: "シャネル" },
  { brand_genre_id: 7, name: "ジルスチュアート" },
  { brand_genre_id: 7, name: "ブルガリ" },
  { brand_genre_id: 7, name: "資生堂" },
  { brand_genre_id: 7, name: "アナスイコスメティックス" },
  { brand_genre_id: 7, name: "カネボウ" },
  { brand_genre_id: 7, name: "ディオール" },
  { brand_genre_id: 7, name: "ドクターシーラボ" },
  { brand_genre_id: 7, name: "ティファニー" },
  { brand_genre_id: 7, name: "サルヴァトーレ　フェラガモ" },
  { brand_genre_id: 7, name: "エスティローダー" },
  { brand_genre_id: 7, name: "ヴェルサーチ" },
  { brand_genre_id: 7, name: "クリスチャンルブタン" },
  { brand_genre_id: 7, name: "グッチ" },
  { brand_genre_id: 7, name: "クロエ" },
  { brand_genre_id: 7, name: "コーチ" },
  { brand_genre_id: 7, name: "ジバンシイ" },
  { brand_genre_id: 7, name: "ニナリッチ" },
  { brand_genre_id: 7, name: "バーバリー" },

  { brand_genre_id: 8, name: "プレイステーション4" },
  { brand_genre_id: 8, name: "Xbox One" },
  { brand_genre_id: 8, name: "ニンテンドースイッチ" },
  { brand_genre_id: 8, name: "ファミコン" },
  { brand_genre_id: 8, name: "スーパーファミコン" },
  { brand_genre_id: 8, name: "ゲームボーイ" },
  { brand_genre_id: 8, name: "ウィー" },
  { brand_genre_id: 8, name: "ウィーユー" },
  { brand_genre_id: 8, name: "ゲームキューブ" },
  { brand_genre_id: 8, name: "Xbox360" },
  { brand_genre_id: 8, name: "Xbox" },
  { brand_genre_id: 8, name: "ニンテンドー3DS" },
  { brand_genre_id: 8, name: "プレイステーションヴィータ" },
  { brand_genre_id: 8, name: "ニンテンドー64" },
  { brand_genre_id: 8, name: "メガドライブ" },
  { brand_genre_id: 8, name: "PCエンジン" },
  { brand_genre_id: 8, name: "ゲームキューブ" },
  { brand_genre_id: 8, name: "プレイステーションポータブル" },
  { brand_genre_id: 8, name: "セガサターン" },
  { brand_genre_id: 8, name: "ドリームキャスト" },
  ])

161.upto(180) do |i|
  Brand.create( name: "スポーツ・レジャー#{i}", brand_genre_id: 9)
end
181.upto(200) do |i|
  Brand.create( name: "スマートフォン#{i}", brand_genre_id: 10)
end
201.upto(220) do |i|
  Brand.create( name: "バイク#{i}", brand_genre_id: 11)
end

Brand.create([
  { brand_genre_id: 12, name: "ヤマハ" },
  { brand_genre_id: 12, name: "ESP" },
  { brand_genre_id: 12, name: "フェンダー" },
  { brand_genre_id: 12, name: "フェルナンデス" },
  { brand_genre_id: 12, name: "ギブソン" },
  { brand_genre_id: 12, name: "キョーリツ" },
  { brand_genre_id: 12, name: "TAMA" },
  { brand_genre_id: 12, name: "スペクター" },
  { brand_genre_id: 12, name: "BOSS" },
  { brand_genre_id: 12, name: "SUZUKI" },
  { brand_genre_id: 12, name: "REON" },
  { brand_genre_id: 12, name: "TOMBO" },
  { brand_genre_id: 12, name: "ビクター" },
  { brand_genre_id: 12, name: "unknown" },
  { brand_genre_id: 12, name: "TOKAI" },
  { brand_genre_id: 12, name: "Combat" },
  { brand_genre_id: 12, name: "Moon" },
  { brand_genre_id: 12, name: "Seed" },
  { brand_genre_id: 12, name: "3M" },
  { brand_genre_id: 12, name: "buzz" },
  ])

241.upto(260) do |i|
  Brand.create( name: "自動車#{i}", brand_genre_id: 13)
end
261.upto(280) do |i|
  Brand.create( name: "食品#{i}", brand_genre_id: 14)
end

user = User.new(nickname: "admin", email: "admin@admin", password: "password")
user.save!

user = User.new(nickname: "龍馬", email: "hoge@hoge", password: "hogehoge")
user.save!

user = User.new(nickname: "半平太", email: "1@1", password: "hogehoge")
user.save!

user = User.new(nickname: "以蔵", email: "2@2", password: "hogehoge")
user.save!

user = User.new(nickname: "万次郎", email: "3@3", password: "hogehoge")
user.save!

user = User.new(nickname: "おりょう", email: "4@4", password: "hogehoge")
user.save!

user = User.new(nickname: "慎太郎", email: "5@5", password: "hogehoge")
user.save!

user = User.new(nickname: "乙女姉ちゃん", email: "6@6", password: "hogehoge")
user.save!

user = User.new(nickname: "弥太郎", email: "7@7", password: "hogehoge")
user.save!

user = User.new(nickname: "退助", email: "8@8", password: "hogehoge")
user.save!



(1..10).each do |i|
  Address.create(
    user_id: i,
    name01: "高知#{i}",
    name02: "土佐#{i}郎",
    name03: "こうち#{i}",
    name04: "とさ#{i}ろう",
    zip: "777-7777",
    state: "高知県",
    city: "高知市",
    address_line: "1-1-1",
    tel: "000-0000-000#{i}",
  )
end

(1..10).each do |i|
  Creditcard.create(
    user_id: i,
    card_number: "****-****-****-7777",
    expiration_month: "04",
    expiration_year: "2018",
    security_code: "777",
  )
end

Item.create(
  name: "シャネル エルメス 水筒",
  image: File.open("./app/assets/images/01.jpg"),
  text: "シャネルの水筒です。表参道の本店で去年購入しました。学生の頃から、十年ほどつかっていますが、まだまだ使えるお品です^^",
  brand_genre_id: 1,
  brand_id: 2,
  category_genre_id: 4,
  category_id: 64,
  quality_status: "目立った傷や汚れなし",
  days:"２〜３日で発送",
  price: 70300,sale_status: 0,
  user_id: 5,
  )

# アイテム追加 カテゴリ レディース 1-5
Item.create(
  name: "サニークラウズ シャツ 花柄",
  image: File.open("./app/assets/images/001001001.jpg"),
  text: "サニークラウズ シャツ 花柄 サニークラウズ シャツ 花柄 サニークラウズ シャツ 花柄",
  brand_genre_id: 1,
  brand_id: 20,
  category_genre_id: 1,
  category_id: 1,
  quality_status: "新品、未使用",
  days:"１〜２日で発送",
  price: 2968,
  sale_status: 0,
  user_id: 10,
)

Item.create(
  name: "しまむら ボーダー ニット",
  image: File.open("./app/assets/images/001001002.jpg"),
  text: "しまむら ボーダー ニット しまむら ボーダー ニット しまむら ボーダー ニット",
  brand_genre_id: 1,
  brand_id: 20,
  category_genre_id: 1,
  category_id: 1,
  quality_status: "新品、未使用",
  days:"１〜２日で発送",
  price: 1500,
  sale_status: 0,
  user_id: 2,
)

Item.create(
  name: "ユニクロ チェック シャツ",
  image: File.open("./app/assets/images/001001003.jpg"),
  text: "ユニクロ チェック シャツ ユニクロ チェック シャツ ユニクロ チェック シャツ",
  brand_genre_id: 1,
  brand_id: 8,
  category_genre_id: 1,
  category_id: 1,
  quality_status: "新品、未使用",
  days:"１〜２日で発送",
  price: 1250,
  sale_status: 0,
  user_id: 2,
)

Item.create(
  name: "ナイキ 半袖 シャツ",
  image: File.open("./app/assets/images/001001004.jpg"),
  text: "ナイキ 半袖 シャツ ナイキ 半袖 シャツ ナイキ 半袖 シャツ",
  brand_genre_id: 1,
  brand_id: 11,
  category_genre_id: 1,
  category_id: 1,
  quality_status: "新品、未使用",
  days:"１〜２日で発送",
  price: 1900,
  sale_status: 0,
  user_id: 9,
)

Item.create(
  name: "ラルフローレン ボーダー Tシャツ",
  image: File.open("./app/assets/images/001001005.jpg"),
  text: "ラルフローレン ボーダー Tシャツ ラルフローレン ボーダー Tシャツ ラルフローレン ボーダー Tシャツ",
  brand_genre_id: 1,
  brand_id: 20,
  category_genre_id: 1,
  category_id: 1,
  quality_status: "新品、未使用",
  days:"１〜２日で発送",
  price: 3000,
  sale_status: 0,
  user_id: 4,
)

Item.create(
  name: "Gジャン デニムジャケット",
  image: File.open("./app/assets/images/001002001.jpg"),
  text: "Gジャン デニムジャケット Gジャン デニムジャケット Gジャン デニムジャケット",
  brand_genre_id: 1,
  brand_id: 20,
  category_genre_id: 1,
  category_id: 2,
  quality_status: "新品、未使用",
  days:"１〜２日で発送",
  price: 1400,
  sale_status: 0,
  user_id: 3,
)

Item.create(
  name: "ユニクロ ウルトラライトダウン",
  image: File.open("./app/assets/images/001002002.jpg"),
  text: "ユニクロ ウルトラライトダウン ユニクロ ウルトラライトダウン ユニクロ ウルトラライトダウン",
  brand_genre_id: 1,
  brand_id: 8,
  category_genre_id: 1,
  category_id: 2,
  quality_status: "目立った傷や汚れなし",
  days:"２〜３日で発送",
  price: 2300,
  sale_status: 0,
  user_id: 3,
)

Item.create(
  name: "ステンカラーコート ショートジャケット",
  image: File.open("./app/assets/images/001002003.jpg"),
  text: "ステンカラーコート ショートジャケット ステンカラーコート ショートジャケット ステンカラーコート ショートジャケット",
  brand_genre_id: 1,
  brand_id: 20,
  category_genre_id: 1,
  category_id: 2,
  quality_status: "目立った傷や汚れなし",
  days:"２〜３日で発送",
  price: 1600,
  sale_status: 0,
  user_id: 7,
)

Item.create(
  name: "ギャップ チェック ダウンベスト",
  image: File.open("./app/assets/images/001002004.jpg"),
  text: "チェック ダウンベスト チェック ダウンベスト チェック ダウンベスト",
  brand_genre_id: 1,
  brand_id: 10,
  category_genre_id: 1,
  category_id: 2,
  quality_status: "目立った傷や汚れなし",
  days:"２〜３日で発送",
  price: 1100,
  sale_status: 0,
  user_id: 6,
)

Item.create(
  name: "ポールスミス ファー付き ダウン",
  image: File.open("./app/assets/images/001002005.jpg"),
  text: "ポールスミス ファー付き ダウン ポールスミス ファー付き ダウン ポールスミス ファー付き ダウン",
  brand_genre_id: 1,
  brand_id: 20,
  category_genre_id: 1,
  category_id: 2,
  quality_status: "目立った傷や汚れなし",
  days:"４〜７日で発送",
  price: 7600,
  sale_status: 0,
  user_id: 5,
)

Item.create(
  name: "デニム ジーンズ レディース",
  image: File.open("./app/assets/images/001003001.jpg"),
  text: "デニム ジーンズ レディース デニム ジーンズ レディース デニム ジーンズ レディース",
  brand_genre_id: 1,
  brand_id: 10,
  category_genre_id: 1,
  category_id: 3,
  quality_status: "新品、未使用",
  days:"１〜２日で発送",
  price: 3500,
  sale_status: 0,
  user_id: 10,
)

Item.create(
  name: "デニム サロペット",
  image: File.open("./app/assets/images/001003002.jpg"),
  text: "デニム サロペット デニム サロペット デニム サロペット",
  brand_genre_id: 1,
  brand_id: 20,
  category_genre_id: 1,
  category_id: 3,
  quality_status: "目立った傷や汚れなし",
  days:"１〜２日で発送",
  price: 1500,
  sale_status: 0,
  user_id: 3,
)

Item.create(
  name: "ユニクロ ジョガーパンツ",
  image: File.open("./app/assets/images/001003003.jpg"),
  text: "ユニクロ ジョガーパンツ ユニクロ ジョガーパンツ ユニクロ ジョガーパンツ",
  brand_genre_id: 1,
  brand_id: 8,
  category_genre_id: 1,
  category_id: 3,
  quality_status: "未使用に近い",
  days:"２〜３日で発送",
  price: 800,
  sale_status: 0,
  user_id: 7,
)

Item.create(
  name: "ユニクロ ハーフパンツ 黒",
  image: File.open("./app/assets/images/001003004.jpg"),
  text: "ユニクロ ハーフパンツ 黒 ユニクロ ハーフパンツ 黒 ユニクロ ハーフパンツ 黒",
  brand_genre_id: 1,
  brand_id: 8,
  category_genre_id: 1,
  category_id: 3,
  quality_status: "未使用に近い",
  days:"４〜７日で発送",
  price: 870,
  sale_status: 0,
  user_id: 2,
)

Item.create(
  name: "GU ショートパンツ",
  image: File.open("./app/assets/images/001003005.jpg"),
  text: "GU ショートパンツ GU ショートパンツ GU ショートパンツ",
  brand_genre_id: 1,
  brand_id: 20,
  category_genre_id: 1,
  category_id: 3,
  quality_status: "新品、未使用",
  days:"１〜２日で発送",
  price: 1000,
  sale_status: 0,
  user_id: 4,
)

Item.create(
  name: "H&M レディース バルーンスカート",
  image: File.open("./app/assets/images/001004001.jpg"),
  text: "H&M レディース バルーンスカート H&M レディース バルーンスカート H&M レディース バルーンスカート",
  brand_genre_id: 1,
  brand_id: 20,
  category_genre_id: 1,
  category_id: 4,
  quality_status: "目立った傷や汚れなし",
  days:"１〜２日で発送",
  price: 1200,
  sale_status: 0,
  user_id: 8,
)

Item.create(
  name: "デニムスカート",
  image: File.open("./app/assets/images/001004002.jpg"),
  text: "デニムスカート デニムスカート デニムスカート",
  brand_genre_id: 1,
  brand_id: 20,
  category_genre_id: 1,
  category_id: 4,
  quality_status: "目立った傷や汚れなし",
  days:"１〜２日で発送",
  price: 1111,
  sale_status: 0,
  user_id: 3,
)

Item.create(
  name: "ナイキ ランニングスカート ピンク",
  image: File.open("./app/assets/images/001004003.jpg"),
  text: "ナイキ ランニングスカート ナイキ ランニングスカート ナイキ ランニングスカート",
  brand_genre_id: 1,
  brand_id: 11,
  category_genre_id: 1,
  category_id: 4,
  quality_status: "新品、未使用",
  days:"１〜２日で発送",
  price: 2000,
  sale_status: 0,
  user_id: 9,
)

Item.create(
  name: "GU フレアスカート 黒",
  image: File.open("./app/assets/images/001004004.jpg"),
  text: "GU フレアスカート 黒 GU フレアスカート 黒 GU フレアスカート 黒",
  brand_genre_id: 1,
  brand_id: 20,
  category_genre_id: 1,
  category_id: 4,
  quality_status: "目立った傷や汚れなし",
  days:"４〜７日で発送",
  price: 1000,
  sale_status: 0,
  user_id: 5,
)

Item.create(
  name: "ギャップ ミニスカート 花柄",
  image: File.open("./app/assets/images/001004005.jpg"),
  text: "ギャップ ミニスカート 花柄 ギャップ ミニスカート 花柄 ギャップ ミニスカート 花柄",
  brand_genre_id: 1,
  brand_id: 10,
  category_genre_id: 1,
  category_id: 4,
  quality_status: "新品、未使用",
  days:"２〜３日で発送",
  price: 500,
  sale_status: 0,
  user_id: 6,
)

Item.create(
  name: "ロペピクニック ワンピース 花柄",
  image: File.open("./app/assets/images/001005001.jpg"),
  text: "ロペピクニック ワンピース 花柄 ロペピクニック ワンピース 花柄 ロペピクニック ワンピース 花柄",
  brand_genre_id: 1,
  brand_id: 20,
  category_genre_id: 1,
  category_id: 5,
  quality_status: "目立った傷や汚れなし",
  days:"１〜２日で発送",
  price: 3500,
  sale_status: 0,
  user_id: 4,
)

Item.create(
  name: "サロペット ワンピース デニム風",
  image: File.open("./app/assets/images/001005002.jpg"),
  text: "サロペット ワンピース デニム風 サロペット ワンピース デニム風 サロペット ワンピース デニム風",
  brand_genre_id: 1,
  brand_id: 20,
  category_genre_id: 1,
  category_id: 5,
  quality_status: "新品、未使用",
  days:"１〜２日で発送",
  price: 1480,
  sale_status: 0,
  user_id: 2,
)

Item.create(
  name: "H&M ワンピース 黒",
  image: File.open("./app/assets/images/001005003.jpg"),
  text: "H&M ワンピース 黒 H&M ワンピース 黒 H&M ワンピース 黒",
  brand_genre_id: 1,
  brand_id: 20,
  category_genre_id: 1,
  category_id: 5,
  quality_status: "未使用に近い",
  days:"４〜７日で発送",
  price: 2000,
  sale_status: 0,
  user_id: 9,
)

Item.create(
  name: "ユニクロ ワンピース ニット",
  image: File.open("./app/assets/images/001005004.jpg"),
  text: "ユニクロ ワンピース ニット ユニクロ ワンピース ニット ユニクロ ワンピース ニット",
  brand_genre_id: 1,
  brand_id: 8,
  category_genre_id: 1,
  category_id: 5,
  quality_status: "目立った傷や汚れなし",
  days:"１〜２日で発送",
  price: 900,
  sale_status: 0,
  user_id: 10,
)

Item.create(
  name: "シャネル コート風 ワンピース 黒",
  image: File.open("./app/assets/images/001005005.jpg"),
  text: "シャネル コート風 ワンピース 黒 シャネル コート風 ワンピース 黒 シャネル コート風 ワンピース 黒",
  brand_genre_id: 1,
  brand_id: 2,
  category_genre_id: 1,
  category_id: 5,
  quality_status: "未使用に近い",
  days:"２〜３日で発送",
  price: 38000,
  sale_status: 0,
  user_id: 8,
)



# アイテム追加 カテゴリ レディース 6-10
Item.create(
  name: "ルイヴィトン くつ",
  image: File.open("./app/assets/images/001006001.jpg"),
  text: "ルイヴィトン くつルイヴィトン くつルイヴィトン くつ",
  brand_genre_id: 1,
  brand_id: 1,
  category_genre_id: 1,
  category_id: 6,
  quality_status: "新品、未使用",
  days:"１〜２日で発送",
  price: 794,
  sale_status: 0,
  user_id: 2,
  )
Item.create(
  name: "シャネル くつ",
  image: File.open("./app/assets/images/001006002.jpg"),
  text: "シャネル くつシャネル くつシャネル くつ",
  brand_genre_id: 1,
  brand_id: 2,
  category_genre_id: 1,
  category_id: 6,
  quality_status: "新品、未使用",
  days:"１〜２日で発送",
  price: 794,
  sale_status: 0,
  user_id: 3,
  )
Item.create(
  name: "フェンディ ヒール 未使用",
  image: File.open("./app/assets/images/001006003.jpg"),
  text: "フェンディ ヒール 未使用フェンディ ヒール 未使用フェンディ ヒール 未使用",
  brand_genre_id: 1,
  brand_id: 3,
  category_genre_id: 1,
  category_id: 6,
  quality_status: "新品、未使用",
  days:"１〜２日で発送",
  price: 794,
  sale_status: 0,
  user_id: 4,
  )
Item.create(
  name: "ルイヴィトン ハイヒール",
  image: File.open("./app/assets/images/001006004.jpg"),
  text: "ルイヴィトン ハイヒールルイヴィトン ハイヒールルイヴィトン ハイヒール",
  brand_genre_id: 1,
  brand_id: 1,
  category_genre_id: 1,
  category_id: 6,
  quality_status: "新品、未使用",
  days:"１〜２日で発送",
  price: 794,
  sale_status: 0,
  user_id: 5,
  )
Item.create(
  name: "シャネル ハイヒール",
  image: File.open("./app/assets/images/001006005.jpg"),
  text: "シャネル ハイヒールシャネル ハイヒールシャネル ハイヒール",
  brand_genre_id: 1,
  brand_id: 2,
  category_genre_id: 1,
  category_id: 6,
  quality_status: "新品、未使用",
  days:"１〜２日で発送",
  price: 794,
  sale_status: 0,
  user_id: 6,
  )
# ルームウェア
Item.create(
  name: "シャネル ルームウェア",
  image: File.open("./app/assets/images/001007001.jpg"),
  text: "シャネル ルームウェアシャネル ルームウェアシャネル ルームウェア",
  brand_genre_id: 1,
  brand_id: 2,
  category_genre_id: 1,
  category_id: 7,
  quality_status: "新品、未使用",
  days:"１〜２日で発送",
  price: 3399,
  sale_status: 0,
  user_id: 7,
  )
Item.create(
  name: "【未使用】シャネル ルームウェア",
  image: File.open("./app/assets/images/001007002.jpg"),
  text: "シャネル ルームウェアシャネル ルームウェアシャネル ルームウェア",
  brand_genre_id: 1,
  brand_id: 2,
  category_genre_id: 1,
  category_id: 7,
  quality_status: "新品、未使用",
  days:"１〜２日で発送",
  price: 3399,
  sale_status: 0,
  user_id: 8,
  )
Item.create(
  name: "アクアガール ルームウェア",
  image: File.open("./app/assets/images/001007003.jpg"),
  text: "アクアガール ルームウェアアクアガール ルームウェアアクアガール ルームウェア",
  brand_genre_id: 1,
  brand_id: 14,
  category_genre_id: 1,
  category_id: 7,
  quality_status: "新品、未使用",
  days:"１〜２日で発送",
  price: 3399,
  sale_status: 0,
  user_id: 9,
  )
Item.create(
  name: "激安！アクアガール ルームウェア",
  image: File.open("./app/assets/images/001007004.jpg"),
  text: "アクアガール ルームウェアアクアガール ルームウェアアクアガール ルームウェア",
  brand_genre_id: 1,
  brand_id: 14,
  category_genre_id: 1,
  category_id: 7,
  quality_status: "新品、未使用",
  days:"１〜２日で発送",
  price: 3399,
  sale_status: 0,
  user_id: 10,
  )
Item.create(
  name: "ヴィトンのパジャマ",
  image: File.open("./app/assets/images/001007005.jpg"),
  text: "ヴィトンのパジャマヴィトンのパジャマヴィトンのパジャマ",
  brand_genre_id: 1,
  brand_id: 1,
  category_genre_id: 1,
  category_id: 7,
  quality_status: "新品、未使用",
  days:"１〜２日で発送",
  price: 3399,
  sale_status: 0,
  user_id: 2,
  )
# レッグウェア
Item.create(
  name: "ヴィトンの靴下 かわいい！",
  image: File.open("./app/assets/images/001008001.jpg"),
  text: "ヴィトンの靴下 かわいいヴィトンの靴下 かわいいヴィトンの靴下 かわいい",
  brand_genre_id: 1,
  brand_id: 1,
  category_genre_id: 1,
  category_id: 8,
  quality_status: "新品、未使用",
  days:"１〜２日で発送",
  price: 4649,
  sale_status: 0,
  user_id: 3,
  )
Item.create(
  name: "【未使用】ヴィトンの靴下",
  image: File.open("./app/assets/images/001008002.jpg"),
  text: "【未使用】ヴィトンの靴下【未使用】ヴィトンの靴下【未使用】ヴィトンの靴下",
  brand_genre_id: 1,
  brand_id: 1,
  category_genre_id: 1,
  category_id: 8,
  quality_status: "新品、未使用",
  days:"１〜２日で発送",
  price: 4649,
  sale_status: 0,
  user_id: 4,
  )
Item.create(
  name: "フェンディ ソックス",
  image: File.open("./app/assets/images/001008003.jpg"),
  text: "フェンディ ソックスフェンディ ソックスフェンディ ソックス",
  brand_genre_id: 1,
  brand_id: 4,
  category_genre_id: 1,
  category_id: 8,
  quality_status: "新品、未使用",
  days:"１〜２日で発送",
  price: 4649,
  sale_status: 0,
  user_id: 5,
  )
Item.create(
  name: "激安！フェンディ ソックス",
  image: File.open("./app/assets/images/001008004.jpg"),
  text: "激安！フェンディ ソックス激安！フェンディ ソックス激安！フェンディ ソックス",
  brand_genre_id: 1,
  brand_id: 4,
  category_genre_id: 1,
  category_id: 8,
  quality_status: "新品、未使用",
  days:"１〜２日で発送",
  price: 4649,
  sale_status: 0,
  user_id: 6,
  )
Item.create(
  name: "アーバンリサーチのくつした（Sサイズ）",
  image: File.open("./app/assets/images/001008005.jpg"),
  text: "アーバンリサーチのくつした（Sサイズ）アーバンリサーチのくつした（Sサイズ）アーバンリサーチのくつした（Sサイズ）",
  brand_genre_id: 1,
  brand_id: 3,
  category_genre_id: 1,
  category_id: 8,
  quality_status: "新品、未使用",
  days:"１〜２日で発送",
  price: 4649,
  sale_status: 0,
  user_id: 7,
  )
# 帽子
Item.create(
  name: "シャネル 帽子 本物！",
  image: File.open("./app/assets/images/001009001.jpg"),
  text: "シャネル 帽子 本物！シャネル 帽子 本物！シャネル 帽子 本物！",
  brand_genre_id: 1,
  brand_id: 2,
  category_genre_id: 1,
  category_id: 9,
  quality_status: "新品、未使用",
  days:"１〜２日で発送",
  price: 343,
  sale_status: 0,
  user_id: 8,
  )
Item.create(
  name: "【未使用】シャネル ハット",
  image: File.open("./app/assets/images/001009002.jpg"),
  text: "【未使用】シャネル ハット【未使用】シャネル ハット【未使用】シャネル ハットア",
  brand_genre_id: 1,
  brand_id: 2,
  category_genre_id: 1,
  category_id: 9,
  quality_status: "新品、未使用",
  days:"１〜２日で発送",
  price: 343,
  sale_status: 0,
  user_id: 9,
  )
Item.create(
  name: "シャネルの帽子 未使用です",
  image: File.open("./app/assets/images/001009003.jpg"),
  text: "シャネルの帽子 未使用ですシャネルの帽子 未使用ですシャネルの帽子 未使用です",
  brand_genre_id: 1,
  brand_id: 2,
  category_genre_id: 1,
  category_id: 9,
  quality_status: "新品、未使用",
  days:"１〜２日で発送",
  price: 343,
  sale_status: 0,
  user_id: 10,
  )
Item.create(
  name: "ヴィトン 帽子 かわいい",
  image: File.open("./app/assets/images/001009004.jpg"),
  text: "ヴィトン 帽子 かわいいヴィトン 帽子 かわいいヴィトン 帽子 かわいい",
  brand_genre_id: 1,
  brand_id: 1,
  category_genre_id: 1,
  category_id: 9,
  quality_status: "新品、未使用",
  days:"１〜２日で発送",
  price: 343,
  sale_status: 0,
  user_id: 2,
  )
Item.create(
  name: "ルイヴィトン 帽子 かわいい",
  image: File.open("./app/assets/images/001009005.jpg"),
  text: "ルイヴィトン 帽子 かわいいルイヴィトン 帽子 かわいいルイヴィトン 帽子 かわいい",
  brand_genre_id: 1,
  brand_id: 1,
  category_genre_id: 1,
  category_id: 9,
  quality_status: "新品、未使用",
  days:"１〜２日で発送",
  price: 343,
  sale_status: 0,
  user_id: 3,
  )
# アクセサリー
Item.create(
  name: "シャネル リング 指輪",
  image: File.open("./app/assets/images/001010001.jpg"),
  text: "シャネル リング 指輪シャネル リング 指輪シャネル リング 指輪",
  brand_genre_id: 1,
  brand_id: 2,
  category_genre_id: 1,
  category_id: 10,
  quality_status: "新品、未使用",
  days:"１〜２日で発送",
  price: 5656,
  sale_status: 0,
  user_id: 4,
  )
Item.create(
  name: "【未使用】シャネル リング 指輪",
  image: File.open("./app/assets/images/001010002.jpg"),
  text: "シャネル リング 指輪シャネル リング 指輪シャネル リング 指輪",
  brand_genre_id: 1,
  brand_id: 2,
  category_genre_id: 1,
  category_id: 10,
  quality_status: "新品、未使用",
  days:"１〜２日で発送",
  price: 5656,
  sale_status: 0,
  user_id: 5,
  )
Item.create(
  name: "シャネル リング 指輪",
  image: File.open("./app/assets/images/001010003.jpg"),
  text: "シャネル リング 指輪シャネル リング 指輪シャネル リング 指輪",
  brand_genre_id: 1,
  brand_id: 2,
  category_genre_id: 1,
  category_id: 10,
  quality_status: "新品、未使用",
  days:"１〜２日で発送",
  price: 5656,
  sale_status: 0,
  user_id: 6,
  )
Item.create(
  name: "激安！ヴィトン指輪 リング",
  image: File.open("./app/assets/images/001010004.jpg"),
  text: "激安！ヴィトン指輪 リング激安！ヴィトン指輪 リング激安！ヴィトン指輪 リング",
  brand_genre_id: 1,
  brand_id: 1,
  category_genre_id: 1,
  category_id: 10,
  quality_status: "新品、未使用",
  days:"１〜２日で発送",
  price: 5656,
  sale_status: 0,
  user_id: 7,
  )
Item.create(
  name: "ヴィトンの指輪 安いよ！",
  image: File.open("./app/assets/images/001010005.jpg"),
  text: "激安！ヴィトン指輪 リング激安！ヴィトン指輪 リング激安！ヴィトン指輪 リング",
  brand_genre_id: 1,
  brand_id: 1,
  category_genre_id: 1,
  category_id: 10,
  quality_status: "新品、未使用",
  days:"１〜２日で発送",
  price: 5656,
  sale_status: 0,
  user_id: 8,
  )


# アイテム追加 カテゴリ レディース 11-15
Item.create(
      name: "シャネル ヘアゴム",
      image: File.open("./app/assets/images/001011001.jpg"),
      text: "シャネル ヘアゴムシャネル ヘアゴムシャネル ヘアゴム",
      brand_genre_id: 1,
      brand_id: 2,
      category_genre_id: 1,
      category_id: 11,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 5000,
      sale_status: 0,
      user_id: 2,
      )
Item.create(
      name: "バレッタ シャネル",
      image: File.open("./app/assets/images/001011002.jpg"),
      text: "バレッタ シャネルバレッタ シャネルバレッタ シャネル",
      brand_genre_id: 1,
      brand_id: 2,
      category_genre_id: 1,
      category_id: 11,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 5000,
      sale_status: 0,
      user_id: 3,
      )
Item.create(
      name: "ヘアアクセサリー バレッタ",
      image: File.open("./app/assets/images/001011003.jpg"),
      text: "ヘアアクセサリー バレッタヘアアクセサリー バレッタヘアアクセサリー バレッタ",
      brand_genre_id: 1,
      brand_id: 20,
      category_genre_id: 1,
      category_id: 11,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 2000,
      sale_status: 0,
      user_id: 4,
      )
Item.create(
      name: "ヘアアクセサリー ヘアゴム",
      image: File.open("./app/assets/images/001011004.jpg"),
      text: "ヘアアクセサリー ヘアゴムヘアアクセサリー ヘアゴムヘアアクセサリー ヘアゴム",
      brand_genre_id: 1,
      brand_id: 20,
      category_genre_id: 1,
      category_id: 11,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 1000,
      sale_status: 0,
      user_id: 5,
      )
Item.create(
      name: "ヘアアクセサリー 小枝アクセサリー",
      image: File.open("./app/assets/images/001011005.jpg"),
      text: "ヘアアクセサリー 小枝アクセサリーヘアアクセサリー 小枝アクセサリーヘアアクセサリー 小枝アクセサリー",
      brand_genre_id: 1,
      brand_id: 20,
      category_genre_id: 1,
      category_id: 11,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 3000,
      sale_status: 0,
      user_id: 6,
      )
Item.create(
      name: "財布 ジルスチュアート",
      image: File.open("./app/assets/images/001012001.jpg"),
      text: "財布 ジルスチュアート財布 ジルスチュアート財布 ジルスチュアート",
      brand_genre_id: 1,
      brand_id: 20,
      category_genre_id: 1,
      category_id: 12,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 39000,
      sale_status: 0,
      user_id: 8,
      )
Item.create(
      name: "財布 COACH",
      image: File.open("./app/assets/images/001012002.jpg"),
      text: "財布 COACH財布 COACH財布 COACH",
      brand_genre_id: 1,
      brand_id: 20,
      category_genre_id: 1,
      category_id: 12,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 59000,
      sale_status: 0,
      user_id: 9,
      )
Item.create(
      name: "キーケース VUITTON",
      image: File.open("./app/assets/images/001012003.jpg"),
      text: "キーケース VUITTONキーケース VUITTONキーケース VUITTON",
      brand_genre_id: 1,
      brand_id: 1,
      category_genre_id: 1,
      category_id: 12,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 29000,
      sale_status: 0,
      user_id: 10,
      )
Item.create(
      name: "キーケース Vivienne",
      image: File.open("./app/assets/images/001012004.jpg"),
      text: "キーケース Vivienneキーケース Vivienneキーケース Vivienne",
      brand_genre_id: 1,
      brand_id: 20,
      category_genre_id: 1,
      category_id: 12,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 19000,
      sale_status: 0,
      user_id: 2,
      )
Item.create(
      name: "財布 vivienne",
      image: File.open("./app/assets/images/001012005.jpg"),
      text: "財布 vivienne財布 vivienne財布 vivienne",
      brand_genre_id: 1,
      brand_id: 20,
      category_genre_id: 1,
      category_id: 12,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 39000,
      sale_status: 0,
      user_id: 3,
      )
Item.create(
      name: "時計 ガガミラノ",
      image: File.open("./app/assets/images/001013001.jpg"),
      text: "時計 ガガミラノ時計 ガガミラノ時計 ガガミラノ",
      brand_genre_id: 1,
      brand_id: 20,
      category_genre_id: 1,
      category_id: 13,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 119000,
      sale_status: 0,
      user_id: 4,
      )
Item.create(
      name: "時計 カルティエ",
      image: File.open("./app/assets/images/001013002.jpg"),
      text: "時計 カルティエ時計 カルティエ時計 カルティエ",
      brand_genre_id: 1,
      brand_id: 20,
      category_genre_id: 1,
      category_id: 13,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 129000,
      sale_status: 0,
      user_id: 5,
      )
Item.create(
      name: "時計 ブルガリ",
      image: File.open("./app/assets/images/001013003.jpg"),
      text: "時計 ブルガリ時計 ブルガリ時計 ブルガリ",
      brand_genre_id: 1,
      brand_id: 20,
      category_genre_id: 1,
      category_id: 13,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 139000,
      sale_status: 0,
      user_id: 6,
      )
Item.create(
      name: "時計 GUCCI",
      image: File.open("./app/assets/images/001013004.jpg"),
      text: "時計 GUCCI時計 GUCCI時計 GUCCI",
      brand_genre_id: 1,
      brand_id: 20,
      category_genre_id: 1,
      category_id: 13,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 149000,
      sale_status: 0,
      user_id: 7,
      )
Item.create(
      name: "時計 vivienne",
      image: File.open("./app/assets/images/001013005.jpg"),
      text: "時計 vivienne時計 vivienne時計 vivienne",
      brand_genre_id: 1,
      brand_id: 20,
      category_genre_id: 1,
      category_id: 13,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 159000,
      sale_status: 0,
      user_id: 8,
      )
Item.create(
      name: "ウィッグ ボブ",
      image: File.open("./app/assets/images/001014001.jpg"),
      text: "ウィッグ ボブウィッグ ボブウィッグ ボブ",
      brand_genre_id: 1,
      brand_id: 20,
      category_genre_id: 1,
      category_id: 14,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 6000,
      sale_status: 0,
      user_id: 10,
      )
Item.create(
      name: "ウィッグ ボブ",
      image: File.open("./app/assets/images/001014002.jpg"),
      text: "ウィッグ ボブウィッグ ボブウィッグ ボブ",
      brand_genre_id: 1,
      brand_id: 20,
      category_genre_id: 1,
      category_id: 14,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 6000,
      sale_status: 0,
      user_id: 2,
      )
Item.create(
      name: "ウィッグ ロング",
      image: File.open("./app/assets/images/001014003.jpg"),
      text: "ウィッグ ロングウィッグ ロングウィッグ ロング",
      brand_genre_id: 1,
      brand_id: 20,
      category_genre_id: 1,
      category_id: 14,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 9000,
      sale_status: 0,
      user_id: 3,
      )
Item.create(
      name: "ウィッグ ロング",
      image: File.open("./app/assets/images/001014004.jpg"),
      text: "ウィッグ ロングウィッグ ロングウィッグ ロング",
      brand_genre_id: 1,
      brand_id: 20,
      category_genre_id: 1,
      category_id: 14,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 9000,
      sale_status: 0,
      user_id: 4,
      )
Item.create(
      name: "ウィッグ ロング",
      image: File.open("./app/assets/images/001014005.jpg"),
      text: "ウィッグ ロングウィッグ ロングウィッグ ロング",
      brand_genre_id: 1,
      brand_id: 20,
      category_genre_id: 1,
      category_id: 14,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 9000,
      sale_status: 0,
      user_id: 5,
      )
Item.create(
      name: "浴衣 紺",
      image: File.open("./app/assets/images/001015001.jpg"),
      text: "浴衣 紺浴衣 紺浴衣 紺",
      brand_genre_id: 1,
      brand_id: 20,
      category_genre_id: 1,
      category_id: 15,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 21000,
      sale_status: 0,
      user_id: 6,
      )
Item.create(
      name: "浴衣 紺 花柄",
      image: File.open("./app/assets/images/001015002.jpg"),
      text: "浴衣 紺 花柄浴衣 紺 花柄浴衣 紺 花柄",
      brand_genre_id: 1,
      brand_id: 20,
      category_genre_id: 1,
      category_id: 15,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 22000,
      sale_status: 0,
      user_id: 7,
      )
Item.create(
      name: "浴衣 白 花柄",
      image: File.open("./app/assets/images/001015003.jpg"),
      text: "浴衣 白 花柄浴衣 白 花柄浴衣 白 花柄",
      brand_genre_id: 1,
      brand_id: 20,
      category_genre_id: 1,
      category_id: 15,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 23000,
      sale_status: 0,
      user_id: 8,
      )
Item.create(
      name: "浴衣 白 金魚",
      image: File.open("./app/assets/images/001015004.jpg"),
      text: "浴衣 白 金魚浴衣 白 金魚浴衣 白 金魚",
      brand_genre_id: 1,
      brand_id: 20,
      category_genre_id: 1,
      category_id: 15,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 24000,
      sale_status: 0,
      user_id: 9,
      )
Item.create(
      name: "浴衣 白 朝顔",
      image: File.open("./app/assets/images/001015005.jpg"),
      text: "浴衣 白 朝顔浴衣 白 朝顔浴衣 白 朝顔",
      brand_genre_id: 1,
      brand_id: 20,
      category_genre_id: 1,
      category_id: 15,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 25000,
      sale_status: 0,
      user_id: 10,
      )


# アイテム追加 カテゴリ レディース 16-20
Item.create(
  name: "伊太利屋 3点セット サマースーツ",
  image: File.open("./app/assets/images/001016001.jpg"),
  text: "伊太利屋のブルーのチェック柄が素敵な3点セットのスーツになります♫サイズ9号",
  brand_genre_id: 1,
  brand_id: 15,
  category_genre_id: 1,
  category_id: 16,
  quality_status: "目立った傷や汚れなし",
  days:"１〜２日で発送",
  price: 3000,sale_status: 0,
  user_id: 10,
  )
Item.create(
  name: "サルヴァトーレフェラガモ 高級ウールスーツ ワンピース 2点セット",
  image: File.open("./app/assets/images/001016002.jpg"),
  text: "サイズ表記:どちらもイタリアサイズ38
【ジャケット】肩幅約37㎝ 袖丈約55.5㎝ 身幅約44㎝ 着丈約59㎝
【ワンピース】肩幅約36.5㎝脇が開いてる部分の一番下約36㎝ ヒップ約46㎝ 着丈約102㎝
裏地あり。
後ろファスナーなので着脱簡単です♪
素材はウールなので、
これからの季節オススメです(^^)
コメントなし即購入大歓迎(*^^*)",
  brand_genre_id: 1,
  brand_id: 12,
  category_genre_id: 1,
  category_id: 16,
  quality_status: "目立った傷や汚れなし",
  days:"１〜２日で発送",
  price: 30000,sale_status: 0,
  user_id: 2,
  )
Item.create(
  name: "BOSCH（ボッシュ) スカートスーツ",
  image: File.open("./app/assets/images/001016003.jpg"),
  text: "BOSCH（ボッシュ) スカートスーツ BOSCH（ボッシュ) スカートスーツ BOSCH（ボッシュ) スカートスーツ",
  brand_genre_id: 1,
  brand_id: 13,
  category_genre_id: 1,
  category_id: 16,
  quality_status: "未使用に近い",
  days:"２〜３日で発送",
  price: 5980,sale_status: 0,
  user_id: 3,
  )
Item.create(
  name: "YVESANTLAURENT スーツ M size",
  image: File.open("./app/assets/images/001016004.jpg"),
  text: "麻混のサンローランのスーツです。(麻45%)sizeはMsize 未使用品です。",
  brand_genre_id: 1,
  brand_id: 9,
  category_genre_id: 1,
  category_id: 16,
  quality_status: "新品、未使用",
  days:"４〜７日で発送",
  price: 17000,sale_status: 0,
  user_id: 4,
  )
Item.create(
  name: "YVES SAINT LAURENTイヴサンローラン スーツ",
  image: File.open("./app/assets/images/001016005.jpg"),
  text: "YVES SAINT LAURENTイヴサンローラン スーツ YVES SAINT LAURENTイヴサンローラン スーツ YVES SAINT LAURENTイヴサンローラン スーツ",
  brand_genre_id: 1,
  brand_id: 9,
  category_genre_id: 1,
  category_id: 16,
  quality_status: "目立った傷や汚れなし",
  days:"１〜２日で発送",
  price: 18300,sale_status: 0,
  user_id: 5,
  )
Item.create(
  name: "【L】新品STUDIO ALPHA ホワイト ツイードスーツ　フォーマル",
  image: File.open("./app/assets/images/001017001.jpg"),
  text: "STUDIO ALPHA ホワイト ツイードスーツ　フォーマル STUDIO ALPHA ホワイト ツイードスーツ　フォーマル STUDIO ALPHA ホワイト ツイードスーツ　フォーマル",
  brand_genre_id: 1,
  brand_id: 20,
  category_genre_id: 1,
  category_id: 17,
  quality_status: "新品、未使用",
  days:"１〜２日で発送",
  price: 5000,sale_status: 0,
  user_id: 6,
  )
Item.create(
  name: "SOUP フォーマルスーツ 上下",
  image: File.open("./app/assets/images/001017002.jpg"),
  text: "●サイズ:ジャケット7号 着丈 約51cm, スカート9号 着丈 約55cm 色は濃いネイビー［細かいドット柄］",
  brand_genre_id: 1,
  brand_id: 20,
  category_genre_id: 1,
  category_id: 17,
  quality_status: "新品、未使用",
  days:"１〜２日で発送",
  price: 5200,sale_status: 0,
  user_id: 7,
  )
Item.create(
  name: "バレンシアガ　ツイードセットアップスーツ　フォーマル",
  image: File.open("./app/assets/images/001017003.jpg"),
  text: "バレンシアガのスカートスーツ。フォーマルスーツ　入学式",
  brand_genre_id: 1,
  brand_id: 15,
  category_genre_id: 1,
  category_id: 17,
  quality_status: "目立った傷や汚れなし",
  days:"１〜２日で発送",
  price: 9500,sale_status: 0,
  user_id: 8,
  )
Item.create(
  name: "HERMES エルメス スーツ ネイビー リネン　フォーマル",
  image: File.open("./app/assets/images/001017004.jpg"),
  text: "デパートのエルメスで購入いたしました。光沢のある上質なリネン素材のスーツです。購入価格は70万円以上致しました。5回程度の着用です。",
  brand_genre_id: 1,
  brand_id: 19,
  category_genre_id: 1,
  category_id: 17,
  quality_status: "目立った傷や汚れなし",
  days:"１〜２日で発送",
  price: 59000,sale_status: 0,
  user_id: 9,
  )
Item.create(
  name: "スピックアンドスパン フォーマルスーツ ジャケット スカート コサージュ セット",
  image: File.open("./app/assets/images/001017005.jpg"),
  text: "フォーマルスーツ。スピック&スパンのツィードジャケット、ViSのスカート、ホワイトの新品コサージュのセット。",
  brand_genre_id: 1,
  brand_id: 20,
  category_genre_id: 1,
  category_id: 17,
  quality_status: "目立った傷や汚れなし",
  days:"１〜２日で発送",
  price: 15000,sale_status: 0,
  user_id: 10,
  )
Item.create(
  name: "ワタベ　ウェディングドレス",
  image: File.open("./app/assets/images/001018001.jpg"),
  text: "ワタベウェディングのドレスになります。※ドレスとグローブとベールのセットになります。",
  brand_genre_id: 1,
  brand_id: 20,
  category_genre_id: 1,
  category_id: 18,
  quality_status: "新品、未使用",
  days:"１〜２日で発送",
  price: 20000,sale_status: 0,
  user_id: 7,
  )
Item.create(
  name: "小枝 ヘアアクセサリー ヘッドドレス",
  image: File.open("./app/assets/images/001018002.jpg"),
  text: "結婚式の披露宴の1度だけ使用しました！ハーフアップなど色々なヘアセットで
使用できるかと思います。",
  brand_genre_id: 1,
  brand_id: 20,
  category_genre_id: 1,
  category_id: 18,
  quality_status: "目立った傷や汚れなし",
  days:"２〜３日で発送",
  price: 900,sale_status: 0,
  user_id: 2,
  )
Item.create(
  name: "TADASHI SHOJI ワンピースドレス",
  image: File.open("./app/assets/images/001018003.jpg"),
  text: "TADASHI SHOJIの華やかでウエストラインが美しい背中あき細身シルエットワンピース・ドレス",
  brand_genre_id: 1,
  brand_id: 5,
  category_genre_id: 1,
  category_id: 18,
  quality_status: "目立った傷や汚れなし",
  days:"２〜３日で発送",
  price: 25500,sale_status: 0,
  user_id: 3,
  )
Item.create(
  name: "sugar Alice 総レースドレス",
  image: File.open("./app/assets/images/001018004.jpg"),
  text: "エメラルドカラーにイエローのレースがとても上品で、首元のビジューもとても華やかです",
  brand_genre_id: 1,
  brand_id: 20,
  category_genre_id: 1,
  category_id: 18,
  quality_status: "目立った傷や汚れなし",
  days:"１〜２日で発送",
  price: 20000,sale_status: 0,
  user_id: 4,
  )
Item.create(
  name: "エメ　オーガンジー パーティードレス",
  image: File.open("./app/assets/images/001018005.jpg"),
  text: "エメのパーティードレスになります。お色味は深い赤です。元は35000円以上したと思います。
sizeは9号となります。",
  brand_genre_id: 1,
  brand_id: 20,
  category_genre_id: 1,
  category_id: 18,
  quality_status: "やや傷や汚れあり",
  days:"４〜７日で発送",
  price: 3580,sale_status: 0,
  user_id: 5,
  )
Item.create(
  name: "ワコール　母子手帳　マタニティ",
  image: File.open("./app/assets/images/001019001.jpg"),
  text: "ワコール　母子手帳　マタニティ　ワコール　母子手帳　マタニティ　ワコール　母子手帳　マタニティ",
  brand_genre_id: 1,
  brand_id: 20,
  category_genre_id: 1,
  category_id: 19,
  quality_status: "新品、未使用",
  days:"４〜７日で発送",
  price: 1111,sale_status: 0,
  user_id: 6,
  )
Item.create(
  name: "Milk tea♪マタニティ♪授乳服♪ボーダー♪アリシアストライプ♪ミルクティー",
  image: File.open("./app/assets/images/001019002.jpg"),
  text: "授乳服兼、マタニティトップスです。Milk tea(ミルクティー)アリシアストライプ",
  brand_genre_id: 1,
  brand_id: 20,
  category_genre_id: 1,
  category_id: 19,
  quality_status: "新品、未使用",
  days:"２〜３日で発送",
  price: 5490,sale_status: 0,
  user_id: 7,
  )
Item.create(
  name: "コート マタニティ",
  image: File.open("./app/assets/images/001019003.jpg"),
  text: "コート マタニティ コート マタニティ コート マタニティ",
  brand_genre_id: 1,
  brand_id: 20,
  category_genre_id: 1,
  category_id: 19,
  quality_status: "目立った傷や汚れなし",
  days:"４〜７日で発送",
  price: 2500,sale_status: 0,
  user_id: 8,
  )
Item.create(
  name: "無印良品パジャマ マタニティ",
  image: File.open("./app/assets/images/001019004.jpg"),
  text: "無印良品パジャマ マタニティ 無印良品パジャマ マタニティ 無印良品パジャマ マタニティ",
  brand_genre_id: 1,
  brand_id: 20,
  category_genre_id: 1,
  category_id: 19,
  quality_status: "やや傷や汚れあり",
  days:"１〜２日で発送",
  price: 1555,sale_status: 0,
  user_id: 9,
  )
Item.create(
  name: "ワコール骨盤ベルト マタニティ",
  image: File.open("./app/assets/images/001019005.jpg"),
  text: "ワコール骨盤ベルト マタニティ ワコール骨盤ベルト マタニティ ワコール骨盤ベルト マタニティ",
  brand_genre_id: 1,
  brand_id: 20,
  category_genre_id: 1,
  category_id: 19,
  quality_status: "やや傷や汚れあり",
  days:"１〜２日で発送",
  price: 3800,sale_status: 0,
  user_id: 10,
  )
Item.create(
  name: "ミニオン ゴーグル コスプレ その他",
  image: File.open("./app/assets/images/001020001.jpg"),
  text: "ミニオン ゴーグル コスプレ その他。新品未使用ですが、元々レンズに傷があります。軽めなので疲れにくいと思います。",
  brand_genre_id: 1,
  brand_id: 20,
  category_genre_id: 1,
  category_id: 20,
  quality_status: "新品、未使用",
  days:"１〜２日で発送",
  price: 900,sale_status: 0,
  user_id: 3,
  )
Item.create(
  name: "サンタセットアップ その他",
  image: File.open("./app/assets/images/001020002.jpg"),
  text: "サンタセットアップ その他。サンタクロースのセットアップです。",
  brand_genre_id: 1,
  brand_id: 20,
  category_genre_id: 1,
  category_id: 20,
  quality_status: "未使用に近い",
  days:"１〜２日で発送",
  price: 1500,sale_status: 0,
  user_id: 2,
  )
Item.create(
  name: "gomme(ゴム) ストール その他",
  image: File.open("./app/assets/images/001020003.jpg"),
  text: "gomme(ゴム) ストール その他。プリントとニットを組み合わせたストール。",
  brand_genre_id: 1,
  brand_id: 20,
  category_genre_id: 1,
  category_id: 20,
  quality_status: "新品、未使用",
  days:"１〜２日で発送",
  price: 17000,sale_status: 0,
  user_id: 3,
  )
Item.create(
  name: "【新品】ペストマスク サバゲー お面 ガスマスク その他",
  image: File.open("./app/assets/images/001020004.jpg"),
  text: "ペストマスク その他。素材： PUレザー。サイズ：29cm×24cm×20cm",
  brand_genre_id: 1,
  brand_id: 20,
  category_genre_id: 1,
  category_id: 20,
  quality_status: "新品、未使用",
  days:"１〜２日で発送",
  price: 5000,sale_status: 0,
  user_id: 4,
  )
Item.create(
  name: "YouTuber ラファエル愛用の仮面 仮装マスク (コスプレ用お面)ハロウィン その他",
  image: File.open("./app/assets/images/001020005.jpg"),
  text: "YouTuber ラファエル愛用の仮面 仮装マスク (コスプレ用お面)ハロウィン その他",
  brand_genre_id: 1,
  brand_id: 20,
  category_genre_id: 1,
  category_id: 20,
  quality_status: "新品、未使用",
  days:"１〜２日で発送",
  price: 1500,sale_status: 0,
  user_id: 5,
  )

# 川原追加
Item.create(
  name: "デニム風パンツ",
  image: File.open("./app/assets/images/pan001.jpg"),
  text: "デニム風パンツ デニム風パンツ デニム風パンツ",
  brand_genre_id: 3,
  brand_id: 20,
  category_genre_id: 3,
  category_id: 3,
  quality_status: "新品、未使用",
  days:"１〜２日で発送",
  price: 700,
  sale_status: 0,
  user_id: 3,
)

Item.create(
  name: "ラルフローレン レギンス パンツ",
  image: File.open("./app/assets/images/pan002.jpg"),
  text: "ラルフローレン レギンス パンツ ラルフローレン レギンス パンツ ラルフローレン レギンス パンツ",
  brand_genre_id: 1,
  brand_id: 20,
  category_genre_id: 3,
  category_id: 3,
  quality_status: "新品、未使用",
  days:"１〜２日で発送",
  price: 1300,
  sale_status: 0,
  user_id: 3,
)

Item.create(
  name: "パンツ 花柄 レギンス",
  image: File.open("./app/assets/images/pan003.jpg"),
  text: "パンツ 花柄 レギンス パンツ 花柄 レギンス パンツ 花柄 レギンス",
  brand_genre_id: 1,
  brand_id: 20,
  category_genre_id: 1,
  category_id: 3,
  quality_status: "新品、未使用",
  days:"１〜２日で発送",
  price: 7000,
  sale_status: 0,
  user_id: 3,
)

Item.create(
  name: "パンツ ナナナナサーカ リメイクデニム",
  image: File.open("./app/assets/images/pan004.jpg"),
  text: "パンツ ナナナナサーカ リメイクデニム",
  brand_genre_id: 2,
  brand_id: 20,
  category_genre_id: 2,
  category_id: 3,
  quality_status: "新品、未使用",
  days:"１〜２日で発送",
  price: 8000,
  sale_status: 0,
  user_id: 9,
)

Item.create(
  name: "パンツ rodeo crowns デニム",
  image: File.open("./app/assets/images/pan005.jpg"),
  text: "パンツ rodeo crowns デニム パンツ rodeo crowns デニム",
  brand_genre_id: 1,
  brand_id: 20,
  category_genre_id: 1,
  category_id: 3,
  quality_status: "新品、未使用",
  days:"１〜２日で発送",
  price: 3600,
  sale_status: 0,
  user_id: 2,
)

Item.create(
  name: "GANRYU サルエルデニムパンツ ガンリュウ コムデギャルソン",
  image: File.open("./app/assets/images/pan006.jpg"),
  text: "GANRYU サルエルデニムパンツ ガンリュウ コムデギャルソン",
  brand_genre_id: 2,
  brand_id: 20,
  category_genre_id: 2,
  category_id: 3,
  quality_status: "新品、未使用",
  days:"１〜２日で発送",
  price: 8000,
  sale_status: 0,
  user_id: 3,
)

Item.create(
  name: "pumpkin デニム ダメージフリンジスキニーパンツ ホワイト",
  image: File.open("./app/assets/images/pan007.jpg"),
  text: "pumpkin デニム ダメージフリンジスキニーパンツ ホワイト",
  brand_genre_id: 1,
  brand_id: 20,
  category_genre_id: 1,
  category_id: 3,
  quality_status: "新品、未使用",
  days:"１〜２日で発送",
  price: 1000,
  sale_status: 0,
  user_id: 4,
)

Item.create(
  name: "EGOIST ダメージデニム パンツ",
  image: File.open("./app/assets/images/pan008.jpg"),
  text: "EGOIST ダメージデニム パンツ EGOIST ダメージデニム パンツ EGOIST ダメージデニム パンツ",
  brand_genre_id: 1,
  brand_id: 20,
  category_genre_id: 1,
  category_id: 3,
  quality_status: "新品、未使用",
  days:"１〜２日で発送",
  price: 1500,
  sale_status: 0,
  user_id: 5,
)

Item.create(
  name: "adidas アディダス プラクティスパンツ",
  image: File.open("./app/assets/images/pan009.jpg"),
  text: "adidas アディダス プラクティスパンツ adidas アディダス プラクティスパンツ",
  brand_genre_id: 3,
  brand_id: 20,
  category_genre_id: 3,
  category_id: 3,
  quality_status: "新品、未使用",
  days:"１〜２日で発送",
  price: 2100,
  sale_status: 0,
  user_id: 6,
)

Item.create(
  name: "ショートパンツ earth music&ecology red label",
  image: File.open("./app/assets/images/pan010.jpg"),
  text: "ショートパンツ earth music&ecology red label ショートパンツ earth music&ecology red label",
  brand_genre_id: 1,
  brand_id: 20,
  category_genre_id: 1,
  category_id: 3,
  quality_status: "新品、未使用",
  days:"１〜２日で発送",
  price: 666,
  sale_status: 0,
  user_id: 7,
)

Item.create(
  name: "さらに値下げしたしniko andのデニム！！今月で売れなければ出品やめます！！パンツ!!",
  image: File.open("./app/assets/images/pan011.jpg"),
  text: "さらに値下げしたしniko andのデニム！！今月で売れなければ出品やめます！！パンツ!!",
  brand_genre_id: 1,
  brand_id: 20,
  category_genre_id: 1,
  category_id: 3,
  quality_status: "新品、未使用",
  days:"１〜２日で発送",
  price: 1600,
  sale_status: 0,
  user_id: 8,
)

Item.create(
  name: "KBF レギンスパンツ",
  image: File.open("./app/assets/images/pan012.jpg"),
  text: "KBF レギンスパンツ KBF レギンスパンツ",
  brand_genre_id: 1,
  brand_id: 20,
  category_genre_id: 1,
  category_id: 3,
  quality_status: "新品、未使用",
  days:"１〜２日で発送",
  price: 1100,
  sale_status: 0,
  user_id: 9,
)

Item.create(
  name: "デニム パンツ",
  image: File.open("./app/assets/images/pan013.jpg"),
  text: "デニム パンツ デニム パンツ",
  brand_genre_id: 2,
  brand_id: 20,
  category_genre_id: 2,
  category_id: 3,
  quality_status: "新品、未使用",
  days:"１〜２日で発送",
  price: 2900,
  sale_status: 0,
  user_id: 10,
)


# メンズアイテム
Item.create(
      name: "ビームス トップス",
      image: File.open("./app/assets/images/002021001.jpg"),
      text: "ビームス トップスビームス トップスビームス トップス",
      brand_genre_id: 2,
      brand_id: 21,
      category_genre_id: 2,
      category_id: 21,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 6900,
      sale_status: 0,
      user_id: 2,
      )
Item.create(
      name: "ビームス トップス",
      image: File.open("./app/assets/images/002021001.jpg"),
      text: "ビームス トップスビームス トップスビームス トップス",
      brand_genre_id: 2,
      brand_id: 21,
      category_genre_id: 2,
      category_id: 21,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 6900,
      sale_status: 0,
      user_id: 2,
      )
Item.create(
      name: "ビームス トップス",
      image: File.open("./app/assets/images/002021002.jpg"),
      text: "ビームス トップスビームス トップスビームス トップス",
      brand_genre_id: 2,
      brand_id: 21,
      category_genre_id: 2,
      category_id: 21,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 5900,
      sale_status: 0,
      user_id: 3,
      )
Item.create(
      name: "RALPHLAUREN トップス",
      image: File.open("./app/assets/images/002021003.jpg"),
      text: "RALPHLAUREN トップスRALPHLAUREN トップスRALPHLAUREN トップス",
      brand_genre_id: 2,
      brand_id: 22,
      category_genre_id: 2,
      category_id: 21,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 7900,
      sale_status: 0,
      user_id: 4,
      )
Item.create(
      name: "RALPHLAUREN トップス",
      image: File.open("./app/assets/images/002021004.jpg"),
      text: "RALPHLAUREN トップスRALPHLAUREN トップスRALPHLAUREN トップス",
      brand_genre_id: 2,
      brand_id: 22,
      category_genre_id: 2,
      category_id: 21,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 7900,
      sale_status: 0,
      user_id: 5,
      )
Item.create(
      name: "UNITED ALLOWS ジャケット/アウター",
      image: File.open("./app/assets/images/002022001.jpg"),
      text: "UNITED ALLOWS ジャケット/アウターUNITED ALLOWS ジャケット/アウターUNITED ALLOWS ジャケット/アウター",
      brand_genre_id: 2,
      brand_id: 23,
      category_genre_id: 2,
      category_id: 22,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 27900,
      sale_status: 0,
      user_id: 6,
      )
Item.create(
      name: "UNITED ALLOWS ジャケット/アウター",
      image: File.open("./app/assets/images/002022002.jpg"),
      text: "UNITED ALLOWS ジャケット/アウターUNITED ALLOWS ジャケット/アウターUNITED ALLOWS ジャケット/アウター",
      brand_genre_id: 2,
      brand_id: 23,
      category_genre_id: 2,
      category_id: 22,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 27900,
      sale_status: 0,
      user_id: 7,
      )
Item.create(
      name: "ARMANI ジャケット/アウター",
      image: File.open("./app/assets/images/002022003.jpg"),
      text: "ARMANI ジャケット/アウターARMANI ジャケット/アウターARMANI ジャケット/アウター",
      brand_genre_id: 2,
      brand_id: 24,
      category_genre_id: 2,
      category_id: 22,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 107900,
      sale_status: 0,
      user_id: 8,
      )
Item.create(
      name: "ARMANI ジャケット/アウター",
      image: File.open("./app/assets/images/002022004.jpg"),
      text: "ARMANI ジャケット/アウターARMANI ジャケット/アウターARMANI ジャケット/アウター",
      brand_genre_id: 2,
      brand_id: 24,
      category_genre_id: 2,
      category_id: 22,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 87900,
      sale_status: 0,
      user_id: 9,
      )
Item.create(
      name: "DIESEL パンツ",
      image: File.open("./app/assets/images/002023001.jpg"),
      text: "DIESEL パンツDIESEL パンツDIESEL パンツ",
      brand_genre_id: 2,
      brand_id: 25,
      category_genre_id: 2,
      category_id: 23,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 37900,
      sale_status: 0,
      user_id: 10,
      )
Item.create(
      name: "DIESEL パンツ",
      image: File.open("./app/assets/images/002023002.jpg"),
      text: "DIESEL パンツDIESEL パンツDIESEL パンツ",
      brand_genre_id: 2,
      brand_id: 25,
      category_genre_id: 2,
      category_id: 23,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 37900,
      sale_status: 0,
      user_id: 2,
      )
Item.create(
      name: "DIESEL パンツ",
      image: File.open("./app/assets/images/002023003.jpg"),
      text: "DIESEL パンツDIESEL パンツDIESEL パンツ",
      brand_genre_id: 2,
      brand_id: 25,
      category_genre_id: 2,
      category_id: 23,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 37900,
      sale_status: 0,
      user_id: 3,
      )
Item.create(
      name: "DIESEL パンツ",
      image: File.open("./app/assets/images/002023004.jpg"),
      text: "DIESEL パンツDIESEL パンツDIESEL パンツ",
      brand_genre_id: 2,
      brand_id: 25,
      category_genre_id: 2,
      category_id: 23,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 37900,
      sale_status: 0,
      user_id: 4,
      )
Item.create(
      name: "キッズ靴 アルマーニジュニア",
      image: File.open("./app/assets/images/003031001.jpg"),
      text: "キッズ靴 アルマーニキッズ靴 アルマーニキッズ靴 アルマーニ",
      brand_genre_id: 3,
      brand_id: 41,
      category_genre_id: 3,
      category_id: 41,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 6900,
      sale_status: 0,
      user_id: 5,
      )
Item.create(
      name: "キッズ靴 アルマーニジュニア",
      image: File.open("./app/assets/images/003031002.jpg"),
      text: "キッズ靴 アルマーニキッズ靴 アルマーニキッズ靴 アルマーニ",
      brand_genre_id: 3,
      brand_id: 41,
      category_genre_id: 3,
      category_id: 41,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 6900,
      sale_status: 0,
      user_id: 6,
      )
Item.create(
      name: "キッズ靴 アルマーニジュニア",
      image: File.open("./app/assets/images/003031003.jpg"),
      text: "キッズ靴 アルマーニキッズ靴 アルマーニキッズ靴 アルマーニ",
      brand_genre_id: 3,
      brand_id: 41,
      category_genre_id: 3,
      category_id: 41,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 4900,
      sale_status: 0,
      user_id: 7,
      )
Item.create(
      name: "キッズ靴 アルマーニジュニア",
      image: File.open("./app/assets/images/003031004.jpg"),
      text: "キッズ靴 アルマーニキッズ靴 アルマーニキッズ靴 アルマーニ",
      brand_genre_id: 3,
      brand_id: 41,
      category_genre_id: 3,
      category_id: 41,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 5900,
      sale_status: 0,
      user_id: 8,
      )
Item.create(
      name: "ベビー服 女の子用 ラルフローレン ベビー",
      image: File.open("./app/assets/images/003032001.jpg"),
      text: "ベビー服 女の子用 ラルフローレン ベビーベビー服 女の子用 ラルフローレン ベビーベビー服 女の子用 ラルフローレン ベビー",
      brand_genre_id: 3,
      brand_id: 42,
      category_genre_id: 3,
      category_id: 42,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 5900,
      sale_status: 0,
      user_id: 9,
      )
Item.create(
      name: "ベビー服 女の子用 ラルフローレン ベビー",
      image: File.open("./app/assets/images/003032002.jpg"),
      text: "ベビー服 女の子用 ラルフローレン ベビーベビー服 女の子用 ラルフローレン ベビーベビー服 女の子用 ラルフローレン ベビー",
      brand_genre_id: 3,
      brand_id: 42,
      category_genre_id: 3,
      category_id: 42,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 4900,
      sale_status: 0,
      user_id: 10,
      )
Item.create(
      name: "ベビー服 女の子用 ラルフローレン ベビー",
      image: File.open("./app/assets/images/003032003.jpg"),
      text: "ベビー服 女の子用 ラルフローレン ベビーベビー服 女の子用 ラルフローレン ベビーベビー服 女の子用 ラルフローレン ベビー",
      brand_genre_id: 3,
      brand_id: 42,
      category_genre_id: 3,
      category_id: 42,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 6900,
      sale_status: 0,
      user_id: 2,
      )
Item.create(
      name: "ベビー服 女の子用 ラルフローレン ベビー",
      image: File.open("./app/assets/images/003032004.jpg"),
      text: "ベビー服 女の子用 ラルフローレン ベビーベビー服 女の子用 ラルフローレン ベビーベビー服 女の子用 ラルフローレン ベビー",
      brand_genre_id: 3,
      brand_id: 42,
      category_genre_id: 3,
      category_id: 42,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 7900,
      sale_status: 0,
      user_id: 3,
      )
Item.create(
      name: "ベビー服 男の子用 ベビー ギャップ",
      image: File.open("./app/assets/images/003033001.jpg"),
      text: "ベビー服 男の子用 ベビー ギャップベビー服 男の子用 ベビー ギャップベビー服 男の子用 ベビー ギャップ",
      brand_genre_id: 3,
      brand_id: 43,
      category_genre_id: 3,
      category_id: 43,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 5900,
      sale_status: 0,
      user_id: 4,
      )
Item.create(
      name: "ベビー服 男の子用 ベビー ギャップ",
      image: File.open("./app/assets/images/003033002.jpg"),
      text: "ベビー服 男の子用 ベビー ギャップベビー服 男の子用 ベビー ギャップベビー服 男の子用 ベビー ギャップ",
      brand_genre_id: 3,
      brand_id: 43,
      category_genre_id: 3,
      category_id: 43,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 4900,
      sale_status: 0,
      user_id: 5,
      )
Item.create(
      name: "ベビー服 男の子用 ベビー ギャップ",
      image: File.open("./app/assets/images/003033003.jpg"),
      text: "ベビー服 男の子用 ベビー ギャップベビー服 男の子用 ベビー ギャップベビー服 男の子用 ベビー ギャップ",
      brand_genre_id: 3,
      brand_id: 43,
      category_genre_id: 3,
      category_id: 43,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 6900,
      sale_status: 0,
      user_id: 6,
      )
Item.create(
      name: "ベビー服 男の子用 ベビー ギャップ",
      image: File.open("./app/assets/images/003033004.jpg"),
      text: "ベビー服 男の子用 ベビー ギャップベビー服 男の子用 ベビー ギャップベビー服 男の子用 ベビー ギャップ",
      brand_genre_id: 3,
      brand_id: 43,
      category_genre_id: 3,
      category_id: 43,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 6900,
      sale_status: 0,
      user_id: 7,
      )
Item.create(
      name: "収納家具 IDÉE",
      image: File.open("./app/assets/images/004041001.jpg"),
      text: "収納家具 IDÉE収納家具 IDÉE収納家具 IDÉE",
      brand_genre_id: 4,
      brand_id: 61,
      category_genre_id: 4,
      category_id: 61,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 26900,
      sale_status: 0,
      user_id: 8,
      )
Item.create(
      name: "収納家具 IDÉE",
      image: File.open("./app/assets/images/004041002.jpg"),
      text: "収納家具 IDÉE収納家具 IDÉE収納家具 IDÉE",
      brand_genre_id: 4,
      brand_id: 61,
      category_genre_id: 4,
      category_id: 61,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 36900,
      sale_status: 0,
      user_id: 9,
      )
Item.create(
      name: "収納家具 TRUCK FURNITURE",
      image: File.open("./app/assets/images/004041003.jpg"),
      text: "収納家具 TRUCK FURNITURE収納家具 TRUCK FURNITURE収納家具 TRUCK FURNITURE",
      brand_genre_id: 4,
      brand_id: 62,
      category_genre_id: 4,
      category_id: 61,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 24800,
      sale_status: 0,
      user_id: 2,
      )
Item.create(
      name: "収納家具 TRUCK FURNITURE",
      image: File.open("./app/assets/images/004041004.jpg"),
      text: "収納家具 TRUCK FURNITURE収納家具 TRUCK FURNITURE収納家具 TRUCK FURNITURE",
      brand_genre_id: 4,
      brand_id: 62,
      category_genre_id: 4,
      category_id: 61,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 34800,
      sale_status: 0,
      user_id: 3,
      )
Item.create(
      name: "椅子/チェア Eames",
      image: File.open("./app/assets/images/004042001.jpg"),
      text: "椅子/チェア Eames椅子/チェア Eames椅子/チェア Eames",
      brand_genre_id: 4,
      brand_id: 63,
      category_genre_id: 4,
      category_id: 62,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 4800,
      sale_status: 0,
      user_id: 4,
      )
Item.create(
      name: "椅子/チェア Eames",
      image: File.open("./app/assets/images/004042002.jpg"),
      text: "椅子/チェア Eames椅子/チェア Eames椅子/チェア Eames",
      brand_genre_id: 4,
      brand_id: 63,
      category_genre_id: 4,
      category_id: 62,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 5800,
      sale_status: 0,
      user_id: 5,
      )
Item.create(
      name: "椅子/チェア Eames",
      image: File.open("./app/assets/images/004042003.jpg"),
      text: "椅子/チェア Eames椅子/チェア Eames椅子/チェア Eames",
      brand_genre_id: 4,
      brand_id: 63,
      category_genre_id: 4,
      category_id: 62,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 6800,
      sale_status: 0,
      user_id: 6,
      )
Item.create(
      name: "椅子/チェア Eames",
      image: File.open("./app/assets/images/004042004.jpg"),
      text: "椅子/チェア Eames椅子/チェア Eames椅子/チェア Eames",
      brand_genre_id: 4,
      brand_id: 63,
      category_genre_id: 4,
      category_id: 62,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 108000,
      sale_status: 0,
      user_id: 7,
      )
Item.create(
      name: "ソファ Francfranc",
      image: File.open("./app/assets/images/004043001.jpg"),
      text: "ソファ Francfrancソファ Francfrancソファ Francfranc",
      brand_genre_id: 4,
      brand_id: 64,
      category_genre_id: 4,
      category_id: 63,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 65800,
      sale_status: 0,
      user_id: 8,
      )
Item.create(
      name: "ソファ Francfranc",
      image: File.open("./app/assets/images/004043002.jpg"),
      text: "ソファ Francfrancソファ Francfrancソファ Francfranc",
      brand_genre_id: 4,
      brand_id: 64,
      category_genre_id: 4,
      category_id: 63,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 44800,
      sale_status: 0,
      user_id: 9,
      )
Item.create(
      name: "ソファ Francfranc",
      image: File.open("./app/assets/images/004043003.jpg"),
      text: "ソファ Francfrancソファ Francfrancソファ Francfranc",
      brand_genre_id: 4,
      brand_id: 64,
      category_genre_id: 4,
      category_id: 63,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 35800,
      sale_status: 0,
      user_id: 10,
      )
Item.create(
      name: "ソファ Francfranc",
      image: File.open("./app/assets/images/004043004.jpg"),
      text: "ソファ Francfrancソファ Francfrancソファ Francfranc",
      brand_genre_id: 4,
      brand_id: 64,
      category_genre_id: 4,
      category_id: 63,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 36800,
      sale_status: 0,
      user_id: 2,
      )

Item.create(
      name: "プレイステーション4 Pro ジェット・ブラック 1TB (CUH-7000BB01)",
      image: File.open("./app/assets/images/005082001.jpg"),
      text: "プレステ4。フルHDテレビをお持ちなら、PS4 ProがPS4のすべてのゲームを1080pに最適化して出力",
      brand_genre_id: 8,
      brand_id: 141,
      category_genre_id: 5,
      category_id: 83,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 33000,sale_status: 0,
      user_id: 5,
)
Item.create(
      name: "プレイステーション4 グランツーリスモSPORT リミテッドエディション [ゲーム機本体]",
      image: File.open("./app/assets/images/005082002.jpg"),
      text: "PlayStation 4 (プレイステーション4) グランツーリスモSPORT リミテッドエディション [ゲーム機本体]",
      brand_genre_id: 8,
      brand_id: 141,
      category_genre_id: 5,
      category_id: 83,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 45000,sale_status: 0,
      user_id: 5,
)
Item.create(
      name: "Nintendo Switch 本体 (ニンテンドースイッチ) 【Joy-Con (L) / (R) グレー】",
      image: File.open("./app/assets/images/005082003.jpg"),
      text: "Nintendo Switch 本体 (ニンテンドースイッチ) 【Joy-Con (L) / (R) グレー】",
      brand_genre_id: 8,
      brand_id: 143,
      category_genre_id: 5,
      category_id: 83,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 35000,sale_status: 0,
      user_id: 9,
)
Item.create(
      name: "Nintendo ニンテンドークラシックミニ スーパーファミコン",
      image: File.open("./app/assets/images/005082004.jpg"),
      text: " Nintendo ニンテンドークラシックミニ スーパーファミコン",
      brand_genre_id: 8,
      brand_id: 145,
      category_genre_id: 5,
      category_id: 83,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 8000,sale_status: 0,
      user_id: 9,
)
Item.create(
      name: "Nintendo ニンテンドークラシックミニ ファミリーコンピュータ",
      image: File.open("./app/assets/images/005082005.jpg"),
      text: "Nintendo ニンテンドークラシックミニ ファミリーコンピュータ",
      brand_genre_id: 8,
      brand_id: 144,
      category_genre_id: 5,
      category_id: 83,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 6500,sale_status: 0,
      user_id: 7,
)
Item.create(
      name: "Nintendo Newニンテンドー3DS LL パールホワイト",
      image: File.open("./app/assets/images/005082006.jpg"),
      text: "Nintendo  Newニンテンドー3DS LL パールホワイト",
      brand_genre_id: 8,
      brand_id: 152,
      category_genre_id: 5,
      category_id: 83,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 20500,sale_status: 0,
      user_id: 7,
)
Item.create(
      name: "Nintendo Newニンテンドー3DS LL メタリックブルー",
      image: File.open("./app/assets/images/005082007.jpg"),
      text: "Nintendo Newニンテンドー3DS LL メタリックブルー",
      brand_genre_id: 8,
      brand_id: 152,
      category_genre_id: 5,
      category_id: 83,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 10500,sale_status: 0,
      user_id: 7,
)
Item.create(
      name: "Xbox One X Forza Horizon 4/Forza Motorsport 7 同梱版",
      image: File.open("./app/assets/images/005082008.jpg"),
      text: "Xbox One X Forza Horizon 4/Forza Motorsport 7 同梱版",
      brand_genre_id: 8,
      brand_id: 142,
      category_genre_id: 5,
      category_id: 83,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 55500,sale_status: 0,
      user_id: 10,
)
Item.create(
      name: "Xbox One Elite ワイヤレスコントローラー (ホワイト スペシャル エディション)",
      image: File.open("./app/assets/images/005082009.jpg"),
      text: "Xbox One Elite ワイヤレスコントローラー (ホワイト スペシャル エディション)",
      brand_genre_id: 8,
      brand_id: 142,
      category_genre_id: 5,
      category_id: 83,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 20500,sale_status: 0,
      user_id: 10,
)
Item.create(
      name: "Xbox One S 500GB Ultra HD ブルーレイ対応プレイヤー Minecraft 同梱版",
      image: File.open("./app/assets/images/005082010.jpg"),
      text: "Xbox One S 500GB Ultra HD ブルーレイ対応プレイヤー Minecraft 同梱版",
      brand_genre_id: 8,
      brand_id: 142,
      category_genre_id: 5,
      category_id: 83,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 29800,sale_status: 0,
      user_id: 10,
)
Item.create(
      name: "Xbox One S 1TB Ultra HDブルーレイ対応プレイヤー Forza Horizon 3 同梱版 ",
      image: File.open("./app/assets/images/005082011.jpg"),
      text: "Xbox One S 1TB Ultra HDブルーレイ対応プレイヤー Forza Horizon 3 同梱版 ",
      brand_genre_id: 8,
      brand_id: 142,
      category_genre_id: 5,
      category_id: 83,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 35800,sale_status: 0,
      user_id: 4,
)
Item.create(
      name: "Xbox One X シャドウ オブ ザ トゥームレイダー 同梱版 (CYV-00111)",
      image: File.open("./app/assets/images/005082012.jpg"),
      text: "Xbox One X シャドウ オブ ザ トゥームレイダー 同梱版 (CYV-00111)",
      brand_genre_id: 8,
      brand_id: 142,
      category_genre_id: 5,
      category_id: 83,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 55200,sale_status: 0,
      user_id: 3,
)

Item.create(
      name: "YAMAHA S90XS【超希少！生産完了品・箱ボロアウトレット超特価！】",
      image: File.open("./app/assets/images/006106001.jpg"),
      text: "生産完了後も高い人気を誇り、プロからも高い評価を得ている88鍵盤ピアノタッチシンセ「YAMAHA S90XS」の箱ボロアウトレット品が完全台数限定超特価",
      brand_genre_id: 12,
      brand_id: 221,
      category_genre_id: 6,
      category_id: 106,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 180000,sale_status: 0,
      user_id: 5,
)
Item.create(
      name: "YAMAHA MODX8【88鍵盤】【入門セット】【kbdset】",
      image: File.open("./app/assets/images/006106002.jpg"),
      text: "フラッグシップモデル「MONTAGE」直系の軽量ピアノタッチシンセ「YAMAHA MODX8」が登場！",
      brand_genre_id: 12,
      brand_id: 221,
      category_genre_id: 6,
      category_id: 106,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 180000,sale_status: 0,
      user_id: 9,
)
Item.create(
      name: "ヤマハ　ブラック・P-515B対応スタンド",
      image: File.open("./app/assets/images/006106003.jpg"),
      text: "YAMAHA L-515B 【ブラック・P-515B対応スタンド】",
      brand_genre_id: 12,
      brand_id: 221,
      category_genre_id: 6,
      category_id: 106,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 15000,sale_status: 0,
      user_id: 9,
)
Item.create(
      name: "スペクター　SPECTOR Euro 5 LX (Ultra Amber)",
      image: File.open("./app/assets/images/006106004.jpg"),
      text: "こちらは通常使用されるトップ材のグレードをより高めた非常に動きのある杢が選定されております。",
      brand_genre_id: 12,
      brand_id: 228,
      category_genre_id: 6,
      category_id: 106,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 280000,sale_status: 0,
      user_id: 9,
)
Item.create(
      name: "フェルナンデス　FERNANDES MB-CUSTOM SEELA【D’ERLANGER, SEELA MODEL】",
      image: File.open("./app/assets/images/006106005.jpg"),
      text: "デランジェ再結成10周年のタイミングにて発売された、SEELA(シーラ)氏の本人仕様のモデル！！ファンなら思わず頷いてしまう、プレイヤーならではの目線も見逃せないところ。",
      brand_genre_id: 12,
      brand_id: 224,
      category_genre_id: 6,
      category_id: 106,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 380000,sale_status: 0,
      user_id: 4,
)
Item.create(
      name: "フェルナンデス　FERNANDES RE-480 IS【D’ERLANGER,CIPHER MODEL】",
      image: File.open("./app/assets/images/006106006.jpg"),
      text: "デランジェ再結成10周年のタイミングにて発売された、鮮烈なパープルラメフレーク、シャープなヘッドデザインが存在感抜群にて多くのファンを持つCIPHER氏のモデル。",
      brand_genre_id: 12,
      brand_id: 224,
      category_genre_id: 6,
      category_id: 106,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 480000,sale_status: 0,
      user_id: 4,
)
Item.create(
      name: "フェンダー　Fender MEX Player Jaguar Bass",
      image: File.open("./app/assets/images/006106007.jpg"),
      text: "フェンダー　Fender MEX Player Jaguar Bass (Tidepool/Maple) [Made In Mexico] 【FENDER THE AUTUMN-WINTER 2018 CAMPAIGN】",
      brand_genre_id: 12,
      brand_id: 223,
      category_genre_id: 6,
      category_id: 106,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 50000,sale_status: 0,
      user_id: 6,
)
Item.create(
      name: "ギブソン　Gibson Thunderbird Bass 2019 (Heritage Cherry Sunburst)",
      image: File.open("./app/assets/images/006106008.jpg"),
      text: "ギブソン　Gibson Thunderbird Bass 2019 (Heritage Cherry Sunburst)",
      brand_genre_id: 12,
      brand_id: 225,
      category_genre_id: 6,
      category_id: 106,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 198000,sale_status: 0,
      user_id: 6,
)
Item.create(
      name: "フェルナンデス　FERNANDES GUSTAVE ”BUCK-TICK",
      image: File.open("./app/assets/images/006106009.jpg"),
      text: "BUCK-TICK 30周年記念モデル！！今井寿氏シグネイチャーモデルの集大成「GUSTAVE」待望の発売開始！",
      brand_genre_id: 12,
      brand_id: 224,
      category_genre_id: 6,
      category_id: 106,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 778000,sale_status: 0,
      user_id: 10,
)
Item.create(
      name: "フェルナンデス　TXL-HH Custom ”BUCK-TICK",
      image: File.open("./app/assets/images/006106010.jpg"),
      text: "BUCK-TICK 30周年記念モデル！！星野英彦氏シグネイチャーモデル「TXL-HH Custom」待望の発売開始！",
      brand_genre_id: 12,
      brand_id: 224,
      category_genre_id: 6,
      category_id: 106,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 518000,sale_status: 0,
      user_id: 10,
)
Item.create(
      name: "フェンダー　Custom Shop MBS 1962 Jazzmaster",
      image: File.open("./app/assets/images/006106011.jpg"),
      text: "フェンダー　Custom Shop MBS 1962 Jazzmaster Relic 3-Tone Sunburst Master Built By Dennis Galuszka S/N R94470 【FENDER CUSTOM SHOP EXHIBITION選定品！】",
      brand_genre_id: 12,
      brand_id: 223,
      category_genre_id: 6,
      category_id: 106,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 898000,sale_status: 2,
      user_id: 8,
)
Item.create(
      name: "ESP J-TVB-V -Maria-",
      image: File.open("./app/assets/images/006106012.jpg"),
      text: "本人直筆サイン入り認定書（シリアルナンバー入り）",
      brand_genre_id: 12,
      brand_id: 222,
      category_genre_id: 6,
      category_id: 106,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 498000,sale_status: 0,
      user_id: 8,
)

Item.create(
      name: "ツイリー ドゥ エルメス 香水",
      image: File.open("./app/assets/images/007124001.jpg"),
      text: "2017年8月29日発売のツイリー ドゥ エルメスです。",
      brand_genre_id: 7,
      brand_id: 121,
      category_genre_id: 7,
      category_id: 124,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 3000,sale_status: 0,
      user_id: 4,
)
Item.create(
      name: "シャネル ココ マドモアゼル オードゥパルファム アンタンス 香水",
      image: File.open("./app/assets/images/007124002.jpg"),
      text: "2018年発売の新作です。",
      brand_genre_id: 7,
      brand_id: 122,
      category_genre_id: 7,
      category_id: 124,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 5000,sale_status: 0,
      user_id: 7,
)
Item.create(
      name: "ブルガリ ローズ ゴルデア オードパルファム 香水",
      image: File.open("./app/assets/images/007124003.jpg"),
      text: "2018年発売の華やかなアニバーサリーエディションのボトルです。",
      brand_genre_id: 7,
      brand_id: 124,
      category_genre_id: 7,
      category_id: 124,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 30000,sale_status: 0,
      user_id: 8,
)
Item.create(
      name: "ブルガリ オムニア ピンク サファイヤ オードトワレ 香水",
      image: File.open("./app/assets/images/007124004.jpg"),
      text: "ピンクサファイアにインスパイアされたキュートな「オムニアピンクサファイヤ」が登場。ピンクポメロやピンクペッパー、ティアレフラワーなど、弾けるようなピンクカラーが放つエネルギーを感じる香り。",
      brand_genre_id: 7,
      brand_id: 124,
      category_genre_id: 7,
      category_id: 124,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 15000,sale_status: 1,
      user_id: 8,
)
Item.create(
      name: "シャネル　2018春夏コレクション ヴェルニ ロング トゥニュ　ネイルカラー",
      image: File.open("./app/assets/images/007123005.jpg"),
      text: "シャネル　LE VERNIS。2018年1月　パリのシャネル１店舗のみで先行発売。",
      brand_genre_id: 7,
      brand_id: 122,
      category_genre_id: 7,
      category_id: 123,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 10000,sale_status: 0,
      user_id: 4,
)
Item.create(
      name: "シャネル Rouge Allure INK アリュール 口紅",
      image: File.open("./app/assets/images/007122006.jpg"),
      text: "シャネル 2018秋 Rouge Allure Ink ルージュアリュールインク",
      brand_genre_id: 7,
      brand_id: 122,
      category_genre_id: 7,
      category_id: 122,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 10000,sale_status: 0,
      user_id: 4,
)
Item.create(
      name: "シャネル　2018年秋　ヴェルヴェット ヴェルニ 2本セット　ネイルカラー",
      image: File.open("./app/assets/images/007123007.jpg"),
      text: "シャネル　2018年秋　ヴェルヴェット ヴェルニ 2本セット　ネイルカラー",
      brand_genre_id: 7,
      brand_id: 122,
      category_genre_id: 7,
      category_id: 123,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 9999,sale_status: 0,
      user_id: 6,
)
Item.create(
      name: "シャネル　LE VERNIS＊2018年春夏コレクション新商品　ネイルカラー",
      image: File.open("./app/assets/images/007123008.jpg"),
      text: "シャネル　LE VERNIS＊2018年春夏コレクション新商品　ネイルカラー",
      brand_genre_id: 7,
      brand_id: 122,
      category_genre_id: 7,
      category_id: 123,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 6999,sale_status: 2,
      user_id: 6,
)
Item.create(
      name: "シャネル 2019年最新☆CHANEL ROUGE COCO GLOSS Trio Set☆グロスセット",
      image: File.open("./app/assets/images/007122009.jpg"),
      text: "シャネルの限定リップグロスセット、今年も２０１８年秋から新作が登場！",
      brand_genre_id: 7,
      brand_id: 122,
      category_genre_id: 7,
      category_id: 122,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 16000,sale_status: 0,
      user_id: 4,
)
Item.create(
      name: "ジルスチュアート JILL STUART 香水",
      image: File.open("./app/assets/images/007124010.jpg"),
      text: "ジルバイ ジルスチュアート 30ml",
      brand_genre_id: 7,
      brand_id: 123,
      category_genre_id: 7,
      category_id: 124,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 7500,sale_status: 1,
      user_id: 4,
)
Item.create(
      name: "ジルスチュアート リラックス オード ホワイトフローラル 香水",
      image: File.open("./app/assets/images/007124011.jpg"),
      text: "ジルスチュアート リラックス オード ホワイトフローラル (オーデコロン) 50ml",
      brand_genre_id: 7,
      brand_id: 123,
      category_genre_id: 7,
      category_id: 124,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 3500,sale_status: 0,
      user_id: 4,
)

Item.create(
  name: "CHANEL シャネル ブラン",
  image: File.open("./app/assets/images/chanel001.jpg"),
  text: "CHANEL シャネル ブラン CHANEL シャネル ブラン CHANEL シャネル ブラン",
  brand_genre_id: 1,
  brand_id: 2,
  category_genre_id: 1,
  category_id: 20,
  quality_status: "新品、未使用",
  days:"１〜２日で発送",
  price: 1200,
  sale_status: 0,
  user_id: 3,
)
Item.create(
  name: "CHANEL シャネル サングラス",
  image: File.open("./app/assets/images/chanel002.jpg"),
  text: "CHANEL シャネル サングラス CHANEL シャネル サングラス CHANEL シャネル サングラス",
  brand_genre_id: 1,
  brand_id: 2,
  category_genre_id: 1,
  category_id: 20,
  quality_status: "新品、未使用",
  days:"１〜２日で発送",
  price: 33333,
  sale_status: 0,
  user_id: 3,
)
Item.create(
  name: "CHANEL シャネル マトラッセ チェーンバッグ",
  image: File.open("./app/assets/images/chanel003.jpg"),
  text: "CHANEL シャネル マトラッセ チェーンバッグ CHANEL シャネル マトラッセ チェーンバッグ CHANEL シャネル マトラッセ チェーンバッグ",
  brand_genre_id: 1,
  brand_id: 2,
  category_genre_id: 1,
  category_id: 20,
  quality_status: "新品、未使用",
  days:"１〜２日で発送",
  price: 160000,
  sale_status: 2,
  user_id: 7,
)
Item.create(
  name: "CHANEL シャネル スカート",
  image: File.open("./app/assets/images/chanel004.jpg"),
  text: "CHANEL シャネル スカート CHANEL シャネル スカート CHANEL シャネル スカート",
  brand_genre_id: 1,
  brand_id: 2,
  category_genre_id: 1,
  category_id: 4,
  quality_status: "新品、未使用",
  days:"１〜２日で発送",
  price: 30000,
  sale_status: 0,
  user_id: 2,
)
Item.create(
  name: "CHANEL シャネル vintage イヤリング",
  image: File.open("./app/assets/images/chanel005.jpg"),
  text: "CHANEL シャネル vintage イヤリング CHANEL シャネル vintage イヤリング CHANEL シャネル vintage イヤリング",
  brand_genre_id: 1,
  brand_id: 2,
  category_genre_id: 1,
  category_id: 11,
  quality_status: "新品、未使用",
  days:"１〜２日で発送",
  price: 8500,
  sale_status: 0,
  user_id: 10,
)
Item.create(
  name: "CHANEL シャネル ブーツ 黒",
  image: File.open("./app/assets/images/chanel006.jpg"),
  text: "CHANEL シャネル ブーツ 黒 CHANEL シャネル ブーツ 黒 CHANEL シャネル ブーツ 黒",
  brand_genre_id: 1,
  brand_id: 2,
  category_genre_id: 1,
  category_id: 6,
  quality_status: "新品、未使用",
  days:"１〜２日で発送",
  price: 63500,
  sale_status: 1,
  user_id: 8,
)
Item.create(
  name: "CHANEL シャネル 化粧ブラシセット",
  image: File.open("./app/assets/images/chanel007.jpg"),
  text: "CHANEL シャネル 化粧ブラシセット CHANEL シャネル 化粧ブラシセット CHANEL シャネル 化粧ブラシセット",
  brand_genre_id: 1,
  brand_id: 2,
  category_genre_id: 7,
  category_id: 20,
  quality_status: "新品、未使用",
  days:"１〜２日で発送",
  price: 2800,
  sale_status: 2,
  user_id: 8,
)
Item.create(
  name: "CHANEL シャネル 口紅 7本セット",
  image: File.open("./app/assets/images/chanel008.jpg"),
  text: "CHANEL シャネル 口紅 7本セット CHANEL シャネル 口紅 7本セット CHANEL シャネル 口紅 7本セット",
  brand_genre_id: 1,
  brand_id: 2,
  category_genre_id: 7,
  category_id: 20,
  quality_status: "新品、未使用",
  days:"１〜２日で発送",
  price: 3000,
  sale_status: 0,
  user_id: 9,
)
Item.create(
  name: "CHANEL シャネル ノベルティポーチ",
  image: File.open("./app/assets/images/chanel009.jpg"),
  text: "CHANEL シャネル ノベルティポーチ CHANEL シャネル ノベルティポーチ CHANEL シャネル ノベルティポーチ",
  brand_genre_id: 1,
  brand_id: 2,
  category_genre_id: 1,
  category_id: 20,
  quality_status: "新品、未使用",
  days:"１〜２日で発送",
  price: 2000,
  sale_status: 0,
  user_id: 9,
)
Item.create(
  name: "CHANEL シャネル パンプス",
  image: File.open("./app/assets/images/chanel010.jpg"),
  text: "CHANEL シャネル パンプス CHANEL シャネル パンプス CHANEL シャネル パンプス",
  brand_genre_id: 1,
  brand_id: 2,
  category_genre_id: 1,
  category_id: 6,
  quality_status: "新品、未使用",
  days:"１〜２日で発送",
  price: 18000,
  sale_status: 0,
  user_id: 9,
)
Item.create(
  name: "CHANEL シャネル ネクタイ",
  image: File.open("./app/assets/images/chanel011.jpg"),
  text: "CHANEL シャネル ネクタイ CHANEL シャネル ネクタイ CHANEL シャネル ネクタイ",
  brand_genre_id: 2,
  brand_id: 2,
  category_genre_id: 2,
  category_id: 28,
  quality_status: "新品、未使用",
  days:"１〜２日で発送",
  price: 2950,
  sale_status: 0,
  user_id: 4,
)
Item.create(
  name: "CHANEL シャネル サングラス",
  image: File.open("./app/assets/images/chanel012.jpg"),
  text: "CHANEL シャネル サングラス CHANEL シャネル サングラス CHANEL シャネル サングラス",
  brand_genre_id: 1,
  brand_id: 2,
  category_genre_id: 1,
  category_id: 1,
  quality_status: "新品、未使用",
  days:"１〜２日で発送",
  price: 2900,
  sale_status: 0,
  user_id: 4,
)
Item.create(
  name: "CHANEL シャネル No.5 LEAU",
  image: File.open("./app/assets/images/chanel013.jpg"),
  text: "CHANEL シャネル No.5 LEAU CHANEL シャネル No.5 LEAU CHANEL シャネル No.5 LEAU",
  brand_genre_id: 1,
  brand_id: 2,
  category_genre_id: 1,
  category_id: 20,
  quality_status: "新品、未使用",
  days:"１〜２日で発送",
  price: 6200,
  sale_status: 0,
  user_id: 10,
)
Item.create(
  name: "CHANEL シャネル ショップ袋",
  image: File.open("./app/assets/images/chanel014.jpg"),
  text: "CHANEL シャネル ショップ袋 CHANEL シャネル ショップ袋 CHANEL シャネル ショップ袋",
  brand_genre_id: 1,
  brand_id: 2,
  category_genre_id: 1,
  category_id: 20,
  quality_status: "新品、未使用",
  days:"１〜２日で発送",
  price: 900,
  sale_status: 0,
  user_id: 10,
)
Item.create(
  name: "CHANEL シャネル フェイクパールイヤリング",
  image: File.open("./app/assets/images/chanel015.jpg"),
  text: "CHANEL シャネル フェイクパールイヤリング CHANEL シャネル フェイクパールイヤリング CHANEL シャネル フェイクパールイヤリング",
  brand_genre_id: 1,
  brand_id: 2,
  category_genre_id: 1,
  category_id: 10,
  quality_status: "新品、未使用",
  days:"１〜２日で発送",
  price: 28000,
  sale_status: 0,
  user_id: 10,
)
Item.create(
  name: "CHANEL シャネル 長財布 キャビアスキン ココマーク",
  image: File.open("./app/assets/images/chanel016.jpg"),
  text: "CHANEL シャネル 長財布 キャビアスキン ココマーク CHANEL シャネル 長財布 キャビアスキン ココマーク CHANEL シャネル 長財布 キャビアスキン ココマーク",
  brand_genre_id: 1,
  brand_id: 2,
  category_genre_id: 1,
  category_id: 20,
  quality_status: "新品、未使用",
  days:"１〜２日で発送",
  price: 10000,
  sale_status: 0,
  user_id: 10,
)
Item.create(
  name: "CHANEL シャネル ヘアアクセサリー ヘアゴム カンボンライン レア 非売品",
  image: File.open("./app/assets/images/chanel017.jpg"),
  text: "CHANEL シャネル ヘアアクセサリー ヘアゴム カンボンライン レア 非売品CHANEL シャネル ヘアアクセサリー ヘアゴム カンボンライン レア 非売品CHANEL シャネル ヘアアクセサリー ヘアゴム カンボンライン レア 非売品",
  brand_genre_id: 1,
  brand_id: 2,
  category_genre_id: 1,
  category_id: 11,
  quality_status: "新品、未使用",
  days:"１〜２日で発送",
  price: 4400,
  sale_status: 0,
  user_id: 10,
)
Item.create(
  name: "CHANEL シャネル ココマークラインストーンネックレス",
  image: File.open("./app/assets/images/chanel018.jpg"),
  text: "CHANEL シャネル ココマークラインストーンネックレス CHANEL シャネル ココマークラインストーンネックレス CHANEL シャネル ココマークラインストーンネックレス",
  brand_genre_id: 1,
  brand_id: 2,
  category_genre_id: 1,
  category_id: 10,
  quality_status: "新品、未使用",
  days:"１〜２日で発送",
  price: 32000,
  sale_status: 0,
  user_id: 10,
)
Item.create(
  name: "CHANEL シャネル ローファー シューズ",
  image: File.open("./app/assets/images/chanel019.jpg"),
  text: "CHANEL シャネル ローファー シューズ CHANEL シャネル ローファー シューズ CHANEL シャネル ローファー シューズ",
  brand_genre_id: 1,
  brand_id: 2,
  category_genre_id: 1,
  category_id: 6,
  quality_status: "新品、未使用",
  days:"１〜２日で発送",
  price: 28000,
  sale_status: 0,
  user_id: 10,
)
Item.create(
  name: "CHANEL シャネル ネックレス",
  image: File.open("./app/assets/images/chanel020.jpg"),
  text: "CHANEL シャネル ネックレス CHANEL シャネル ネックレス CHANEL シャネル ネックレス",
  brand_genre_id: 1,
  brand_id: 2,
  category_genre_id: 1,
  category_id: 11,
  quality_status: "新品、未使用",
  days:"１〜２日で発送",
  price: 19999,
  sale_status: 0,
  user_id: 10,
)
Item.create(
  name: "シャネル ココボタン　バック レディース",
  image: File.open("./app/assets/images/chanel100.jpg"),
  text: "シャネル ココボタンシリーズのピンク色のバックです。２回ほど使用しましたがお値打ちだと思います。",
  brand_genre_id: 1,
  brand_id: 2,
  category_genre_id: 1,
  category_id: 20,
  quality_status: "未使用に近い",
  days:"２〜３日で発送",
  price: 48000,
  sale_status: 0,
  user_id: 8,
)
2.times do
  Item.create(
    name: "シャネル Chanel 二つ折り財布 財布 コンパクトサイズ ブラック×ゴールド ココボタン レディース",
    image: File.open("./app/assets/images/chanel101.jpg"),
    text: "シャネル Chanel 二つ折り財布 財布 コンパクトサイズ ブラック×ゴールド ココボタン レディース",
    brand_genre_id: 1,
    brand_id: 2,
    category_genre_id: 1,
    category_id: 12,
    quality_status: "未使用に近い",
    days:"２〜３日で発送",
    price: 22000,
    sale_status: 0,
    user_id: 10,
  )
  Item.create(
    name: "シャネル CHANEL バニティ ハンドバッグ ニュートラベルライン イエロー キャンバス×レザー",
    image: File.open("./app/assets/images/chanel102.jpg"),
    text: "シャネル CHANEL バニティ ハンドバッグ ニュートラベルライン イエロー キャンバス×レザー",
    brand_genre_id: 1,
    brand_id: 2,
    category_genre_id: 1,
    category_id: 20,
    quality_status: "未使用に近い",
    days:"２〜３日で発送",
    price: 16800,
    sale_status: 0,
    user_id: 5,
  )
  Item.create(
    name: "シャネル CHANEL トートバッグ ショルダーバッグ レディース ロゴ入り チョコバー ベージュ×オレンジ ビニール",
    image: File.open("./app/assets/images/chanel103.jpg"),
    text: "シャネル CHANEL トートバッグ ショルダーバッグ レディース ロゴ入り チョコバー ベージュ×オレンジ ビニール",
    brand_genre_id: 1,
    brand_id: 2,
    category_genre_id: 1,
    category_id: 20,
    quality_status: "未使用に近い",
    days:"２〜３日で発送",
    price: 38000,
    sale_status: 1,
    user_id: 2,
  )
  Item.create(
    name: "シャネル CHANEL ハンドバッグ ニュートラベルライン ベージュ キャンバス×レザー",
    image: File.open("./app/assets/images/chanel104.jpg"),
    text: "シャネル CHANEL ハンドバッグ ニュートラベルライン ベージュ キャンバス×レザー",
    brand_genre_id: 1,
    brand_id: 2,
    category_genre_id: 1,
    category_id: 20,
    quality_status: "未使用に近い",
    days:"２〜３日で発送",
    price: 32800,
    sale_status: 0,
    user_id: 4,
  )
  Item.create(
    name: "シャネル CHANEL トートバッグ バッチワーク ベージュ×ブルー ビニール",
    image: File.open("./app/assets/images/chanel105.jpg"),
    text: "シャネル CHANEL トートバッグ バッチワーク ベージュ×ブルー ビニール",
    brand_genre_id: 1,
    brand_id: 2,
    category_genre_id: 1,
    category_id: 20,
    quality_status: "未使用に近い",
    days:"２〜３日で発送",
    price: 31800,
    sale_status: 2,
    user_id: 6,
  )
  Item.create(
    name: "シャネル CHANEL ショルダーバッグ チェーンショルダー レディース マトラッセ ブラック×ゴールド レザー",
    image: File.open("./app/assets/images/chanel106.jpg"),
    text: "シャネル CHANEL ショルダーバッグ チェーンショルダー レディース マトラッセ ブラック×ゴールド レザー",
    brand_genre_id: 1,
    brand_id: 2,
    category_genre_id: 1,
    category_id: 20,
    quality_status: "未使用に近い",
    days:"２〜３日で発送",
    price: 99800,
    sale_status: 0,
    user_id: 6,
  )
  Item.create(
    name: "CHANEL シャネル ピアス",
    image: File.open("./app/assets/images/chanel107.jpg"),
    text: "CHANEL シャネル ピアス",
    brand_genre_id: 1,
    brand_id: 2,
    category_genre_id: 1,
    category_id: 10,
    quality_status: "未使用に近い",
    days:"２〜３日で発送",
    price: 25700,
    sale_status: 0,
    user_id: 3,
  )
  Item.create(
    name: "シャネル CHANEL サンプル 美容液 クリーム",
    image: File.open("./app/assets/images/chanel108.jpg"),
    text: "シャネル CHANEL サンプル 美容液 クリーム",
    brand_genre_id: 1,
    brand_id: 2,
    category_genre_id: 1,
    category_id: 20,
    quality_status: "未使用に近い",
    days:"２〜３日で発送",
    price: 2500,
    sale_status: 0,
    user_id: 7,
  )
  Item.create(
    name: "シャネル CHANEL ビンテージイヤリング",
    image: File.open("./app/assets/images/chanel109.jpg"),
    text: "シャネル CHANEL ビンテージイヤリング",
    brand_genre_id: 1,
    brand_id: 2,
    category_genre_id: 1,
    category_id: 10,
    quality_status: "未使用に近い",
    days:"２〜３日で発送",
    price: 11500,
    sale_status: 1,
    user_id: 3,
  )
  Item.create(
    name: "海外限定品 CHANEL シャネル メイクパレット",
    image: File.open("./app/assets/images/chanel110.jpg"),
    text: "海外限定品 CHANEL シャネル メイクパレット",
    brand_genre_id: 1,
    brand_id: 2,
    category_genre_id: 1,
    category_id: 20,
    quality_status: "未使用に近い",
    days:"２〜３日で発送",
    price: 1850,
    sale_status: 1,
    user_id: 7,
  )
  Item.create(
    name: "シャネル CHANEL ポーチ",
    image: File.open("./app/assets/images/chanel111.jpg"),
    text: "シャネル CHANEL ポーチ",
    brand_genre_id: 1,
    brand_id: 2,
    category_genre_id: 1,
    category_id: 20,
    quality_status: "未使用に近い",
    days:"２〜３日で発送",
    price: 5550,
    sale_status: 0,
    user_id: 5,
  )
  Item.create(
    name: "VD26 シャネル ココマークイヤリング スイング ターンロック ラインストーン",
    image: File.open("./app/assets/images/chanel112.jpg"),
    text: "VD26 シャネル ココマークイヤリング スイング ターンロック ラインストーン",
    brand_genre_id: 1,
    brand_id: 2,
    category_genre_id: 1,
    category_id: 10,
    quality_status: "未使用に近い",
    days:"２〜３日で発送",
    price: 19550,
    sale_status: 0,
    user_id: 3,
  )
  Item.create(
    name: "CHANEL シャネル ピアス",
    image: File.open("./app/assets/images/chanel113.jpg"),
    text: "CHANEL シャネル ピアス",
    brand_genre_id: 1,
    brand_id: 2,
    category_genre_id: 1,
    category_id: 10,
    quality_status: "未使用に近い",
    days:"２〜３日で発送",
    price: 21550,
    sale_status: 2,
    user_id: 7,
  )
  Item.create(
    name: "CHANEL シャネル がま口 ダブルチェーンショルダーバッグ ハンドバッグ",
    image: File.open("./app/assets/images/chanel114.jpg"),
    text: "CHANEL シャネル がま口 ダブルチェーンショルダーバッグ ハンドバッグ",
    brand_genre_id: 1,
    brand_id: 2,
    category_genre_id: 1,
    category_id: 20,
    quality_status: "未使用に近い",
    days:"２〜３日で発送",
    price: 80000,
    sale_status: 0,
    user_id: 7,
  )
  Item.create(
    name: "CHANEL シャネル カメリア 長財布",
    image: File.open("./app/assets/images/chanel115.jpg"),
    text: "CHANEL シャネル カメリア 長財布",
    brand_genre_id: 1,
    brand_id: 2,
    category_genre_id: 1,
    category_id: 20,
    quality_status: "未使用に近い",
    days:"２〜３日で発送",
    price: 18000,
    sale_status: 0,
    user_id: 4,
  )
  Item.create(
    name: "限定お値下げ正規品！美品！CHANELシャネル サンダル",
    image: File.open("./app/assets/images/chanel116.jpg"),
    text: "限定お値下げ正規品！美品！CHANELシャネル サンダル",
    brand_genre_id: 1,
    brand_id: 2,
    category_genre_id: 1,
    category_id: 20,
    quality_status: "未使用に近い",
    days:"２〜３日で発送",
    price: 21800,
    sale_status: 0,
    user_id: 7,
  )
  Item.create(
    name: "リップ柄、デカマトラッセ CHANELシャネル",
    image: File.open("./app/assets/images/chanel117.jpg"),
    text: "リップ柄、デカマトラッセ CHANELシャネル",
    brand_genre_id: 1,
    brand_id: 2,
    category_genre_id: 1,
    category_id: 20,
    quality_status: "未使用に近い",
    days:"２〜３日で発送",
    price: 121800,
    sale_status: 2,
    user_id: 5,
  )
  Item.create(
    name: "正規品 美品 シャネル ショルダー ストラップ スポーツ  CHANEL",
    image: File.open("./app/assets/images/chanel118.jpg"),
    text: "正規品 美品 シャネル ショルダー ストラップ スポーツ  CHANEL",
    brand_genre_id: 1,
    brand_id: 2,
    category_genre_id: 1,
    category_id: 20,
    quality_status: "未使用に近い",
    days:"２〜３日で発送",
    price: 121800,
    sale_status: 0,
    user_id: 3,
  )
  Item.create(
    name: "シャネル 衣装カバー CHANEL",
    image: File.open("./app/assets/images/chanel119.jpg"),
    text: "正規品 中古 黒ナイロン製 CHANEL",
    brand_genre_id: 1,
    brand_id: 2,
    category_genre_id: 1,
    category_id: 20,
    quality_status: "未使用に近い",
    days:"２〜３日で発送",
    price: 2800,
    sale_status: 1,
    user_id: 2,
  )
  Item.create(
    name: "シャネル ココマークラインストーンネックレス CHANEL",
    image: File.open("./app/assets/images/chanel120.jpg"),
    text: "購入時に試着してますが、付けて外出はしてません。",
    brand_genre_id: 1,
    brand_id: 2,
    category_genre_id: 1,
    category_id: 10,
    quality_status: "未使用に近い",
    days:"２〜３日で発送",
    price: 32000,
    sale_status: 0,
    user_id: 10,
  )
end

Comment.create(
 text: "素敵なお品ですね。
おいくらまででしたらお値引きは可能でしょうか？
失礼なコメントをして申し訳ございません >_< ",
  item_id: 1,
  user_id: 8,
)
Comment.create(
 text: "ありがとうございます。即決でしたら一万円のお値引きさせていただきます^_^
 ご検討よろしくお願いします。",
 item_id: 1,
 user_id: 5,
)
Comment.create(
 text: "ご返答ありがとうございます。
 また、お値引きの件もありがとうございます。
 確認させていただきたいのですが、水筒の底や背面の画像を見せていただくことは可能でしょうか？",
 item_id: 1,
 user_id: 8,
)
Comment.create(
 text: "ご質問ありがとうございます。
 とりあえず背面を撮影しました。
 よろしくお願いします。",
 item_id: 1,
 user_id: 5,
 comment_image: File.open("./app/assets/images/01_02.jpg")
)
Comment.create(
 text: "ユーズド品のため、底には小さな傷があります。
 よろしくお願いします。",
 item_id: 1,
 user_id: 5,
 comment_image: File.open("./app/assets/images/01_03.jpg")
)
Comment.create(
 text: "ご丁寧にありがとうございます。
購入を検討しておりますが、フタの開閉については問題ないでしょうか？
質問ばかりで申し訳ございません　>_< ",
 item_id: 1,
 user_id: 8,
)
Comment.create(
 text: "ご質問ありがとうございます。
 フタの開閉を動画で撮影しました！
 ご検討よろしくお願いします。",
 item_id: 1,
 user_id: 5,
 video: File.open("./app/assets/images/video01.MOV")
)
Comment.create(
 text: "ご丁寧にありがとうございます。
購入を検討しておりますが、6万円にして頂くことは厳しいでしょうか？
大変不躾なお願いをして申し訳ございません　>_< ",
 item_id: 1,
 user_id: 8,
)
Comment.create(
  text: "こんにちは^_^まだ手元に置いておきたい気持ちと、悩みながら本日限りで6万円にさせていただきます。
  ご検討よろしくお願いします。",
  item_id: 1,
  user_id: 5,
)
Comment.create(
  text: "お値引きありがとうございます！
  さっそく購入させていただきました。
  よろしくお願いします！",
  item_id: 1,
  user_id: 8,
)
