CategoryGenre.create([
  { name: "レディース" },
  { name: "メンズ" },
  { name: "ベビー・キッズ" },
  { name: "インテリア・住まい" },
  { name: "本・音楽・ゲーム" },
  { name: "おもちゃ・ホビー" },
  { name: "コスメ・香水・美容" },
  { name: "家電・スマホ・カメラ" },
  { name: "スポーツ・レジャー" },
  { name: "ハンドメイド" },
  { name: "チケット" },
  { name: "自転車・オートバイ" },
  { name: "その他" },
  ])

Category.create([
  {category_genre_id: 1, name: "トップス"},
  {category_genre_id: 1, name: "ジャケット/アウター"},
  {category_genre_id: 1, name: "パンツ"},
  {category_genre_id: 1, name: "スカート"},
  {category_genre_id: 1, name: "ワンピース"},
  {category_genre_id: 1, name: "靴"},
  {category_genre_id: 1, name: "ルームウェア"},
  {category_genre_id: 1, name: "レッグウェア"},
  {category_genre_id: 1, name: "帽子"},
  {category_genre_id: 1, name: "アクセサリー"},
  {category_genre_id: 1, name: "ヘアアクセサリー"},
  {category_genre_id: 1, name: "小物"},
  {category_genre_id: 1, name: "時計"},
  {category_genre_id: 1, name: "ウィッグ/エクステ"},
  {category_genre_id: 1, name: "浴衣/水着"},
  {category_genre_id: 1, name: "スーツ"},
  {category_genre_id: 1, name: "フォーマル"},
  {category_genre_id: 1, name: "ドレス"},
  {category_genre_id: 1, name: "マタニティ"},
  {category_genre_id: 1, name: "その他"},
  ])

Category.create([
  {category_genre_id: 2, name: "トップス"},
  {category_genre_id: 2, name: "ジャケット/アウター"},
  {category_genre_id: 2, name: "パンツ"},
  {category_genre_id: 2, name: "靴"},
  {category_genre_id: 2, name: "バック"},
  {category_genre_id: 2, name: "スーツ"},
  {category_genre_id: 2, name: "帽子"},
  {category_genre_id: 2, name: "アクセサリー"},
  {category_genre_id: 2, name: "小物"},
  {category_genre_id: 2, name: "時計"},
  {category_genre_id: 2, name: "レッグウェア"},
  {category_genre_id: 2, name: "アンダーウェア"},
  {category_genre_id: 2, name: "スポーツ"},
  {category_genre_id: 2, name: "ウィッグ"},
  {category_genre_id: 2, name: "浴衣"},
  {category_genre_id: 2, name: "カジュアル"},
  {category_genre_id: 2, name: "フォーマル"},
  {category_genre_id: 2, name: "ルームウェア"},
  {category_genre_id: 2, name: "ビジネス"},
  {category_genre_id: 2, name: "その他"},
  ])
Category.create([
  {category_genre_id: 3, name: "キッズ靴"},
  {category_genre_id: 3, name: "ベビー服(女の子用) ~95cm"},
  {category_genre_id: 3, name: "ベビー服(男の子用) ~95cm"},
  {category_genre_id: 3, name: "ベビー服(男女兼用) ~95cm"},
  {category_genre_id: 3, name: "キッズ服(女の子用) 100cm~"},
  {category_genre_id: 3, name: "キッズ服(男の子用) 100cm~"},
  {category_genre_id: 3, name: "キッズ服(男女兼用) 100cm~"},
  {category_genre_id: 3, name: "子ども用ファッション小物"},
  {category_genre_id: 3, name: "おむつ/トイレ/バス"},
  {category_genre_id: 3, name: "トイレ/バス"},
  {category_genre_id: 3, name: "外出/移動用品"},
  {category_genre_id: 3, name: "授乳/食事"},
  {category_genre_id: 3, name: "ベビー家具"},
  {category_genre_id: 3, name: "寝具"},
  {category_genre_id: 3, name: "おもちゃ"},
  {category_genre_id: 3, name: "行事/記念品"},
  {category_genre_id: 3, name: "フォーマル"},
  {category_genre_id: 3, name: "ルームウェア"},
  {category_genre_id: 3, name: "室内用品"},
  {category_genre_id: 3, name: "その他"},
  ])
Category.create([
  {category_genre_id: 4, name: "収納家具"},
  {category_genre_id: 4, name: "椅子/チェア"},
  {category_genre_id: 4, name: "ソファ"},
  {category_genre_id: 4, name: "キッチン"},
  {category_genre_id: 4, name: "食器"},
  {category_genre_id: 4, name: "ベッド"},
  {category_genre_id: 4, name: "マットレス"},
  {category_genre_id: 4, name: "ソファベッド"},
  {category_genre_id: 4, name: "机/テーブル"},
  {category_genre_id: 4, name: "ラグ"},
  {category_genre_id: 4, name: "カーペット/マット"},
  {category_genre_id: 4, name: "カーテン"},
  {category_genre_id: 4, name: "ライト/照明"},
  {category_genre_id: 4, name: "寝具"},
  {category_genre_id: 4, name: "インテリア小物"},
  {category_genre_id: 4, name: "季節"},
  {category_genre_id: 4, name: "年中行事"},
  {category_genre_id: 4, name: "ブラインド"},
  {category_genre_id: 4, name: "テーブル"},
  {category_genre_id: 4, name: "その他"},
  ])
Category.create([
  {category_genre_id: 5, name: "CD"},
  {category_genre_id: 5, name: "本"},
  {category_genre_id: 5, name: "テレビゲーム"},
  {category_genre_id: 5, name: "DVD/ブルーレイ"},
  {category_genre_id: 5, name: "雑誌"},
  {category_genre_id: 5, name: "漫画"},
  {category_genre_id: 5, name: "レコード"},
  {category_genre_id: 5, name: "LP"},
  {category_genre_id: 5, name: "カードゲーム"},
  {category_genre_id: 5, name: "TRPG"},
  {category_genre_id: 5, name: "ミニチュアゲーム"},
  {category_genre_id: 5, name: "ボードゲーム"},
  {category_genre_id: 5, name: "カードゲーム"},
  {category_genre_id: 5, name: "ドミノ"},
  {category_genre_id: 5, name: "ダイスゲーム"},
  {category_genre_id: 5, name: "麻雀"},
  {category_genre_id: 5, name: "筐体"},
  {category_genre_id: 5, name: "ビデオ"},
  {category_genre_id: 5, name: "フィルム"},
  {category_genre_id: 5, name: "その他"},
  ])

Category.create([
  {category_genre_id: 6, name: "おもちゃ"},
  {category_genre_id: 6, name: "タレントグッズ"},
  {category_genre_id: 6, name: "コミック/アニメグッズ"},
  {category_genre_id: 6, name: "浮世絵"},
  {category_genre_id: 6, name: "フィギュア"},
  {category_genre_id: 6, name: "楽器/器材"},
  {category_genre_id: 6, name: "コレクション"},
  {category_genre_id: 6, name: "ミリタリー"},
  {category_genre_id: 6, name: "陶芸"},
  {category_genre_id: 6, name: "ガラス"},
  {category_genre_id: 6, name: "漆芸"},
  {category_genre_id: 6, name: "金属工芸"},
  {category_genre_id: 6, name: "絵画/タペストリ"},
  {category_genre_id: 6, name: "トレーディングカード"},
  {category_genre_id: 6, name: "版画"},
  {category_genre_id: 6, name: "彫刻/オブジェクト"},
  {category_genre_id: 6, name: "書"},
  {category_genre_id: 6, name: "写真"},
  {category_genre_id: 6, name: "アート用品"},
  {category_genre_id: 6, name: "その他"},
  ])

Category.create([
  { category_genre_id: 7, name: "ベースメイク"},
  { category_genre_id: 7, name: "メイクアップ"},
  { category_genre_id: 7, name: "ネイルカラー"},
  { category_genre_id: 7, name: "香水（女性用）"},
  { category_genre_id: 7, name: "香水（男性用）"},
  { category_genre_id: 7, name: "ネイルアート用品"},
  { category_genre_id: 7, name: "ネイルパーツ"},
  { category_genre_id: 7, name: "ネイルチップ/付け爪"},
  { category_genre_id: 7, name: "美顔用品/美顔ローラー"},
  { category_genre_id: 7, name: "フットケア"},
  { category_genre_id: 7, name: "芳香器"},
  { category_genre_id: 7, name: "メイク道具/化粧小物"},
  { category_genre_id: 7, name: "基礎化粧品"},
  { category_genre_id: 7, name: "スキンケア"},
  { category_genre_id: 7, name: "ヘアケア"},
  { category_genre_id: 7, name: "ボディケア"},
  { category_genre_id: 7, name: "オーラルケア"},
  { category_genre_id: 7, name: "リラクゼーション"},
  { category_genre_id: 7, name: "ダイエット"},
  { category_genre_id: 7, name: "その他"},
  ])

141.upto(160) do |i|
  Category.create( name: "家電#{i}", category_genre_id: 8)
end
161.upto(180) do |i|
  Category.create( name: "スポーツ#{i}", category_genre_id: 9)
end
181.upto(200) do |i|
  Category.create( name: "ハンドメイド#{i}", category_genre_id: 10)
end
201.upto(220) do |i|
  Category.create( name: "チケット#{i}", category_genre_id: 11)
end
221.upto(240) do |i|
  Category.create( name: "自動車#{i}", category_genre_id: 12)
end
241.upto(260) do |i|
  Category.create( name: "その他#{i}", category_genre_id: 13)
end


BrandGenre.create([
  { name: "レディース" },
  { name: "メンズ" },
  { name: "ベビー・キッズ" },
  { name: "インテリア・住まい" },
  { name: "キッチン・食器" },
  { name: "時計" },
  { name: "コスメ・香水・美容" },
  { name: "テレビゲーム" },
  { name: "スポーツ・レジャー" },
  { name: "スマートフォン" },
  { name: "バイク" },
  { name: "楽器" },
  { name: "自動車" },
  { name: "食品" },
  ])

Brand.create([
  { brand_genre_id: 1, name: "ルイヴィトン" },
  { brand_genre_id: 1, name: "シャネル" },
  { brand_genre_id: 1, name: "アーバンリサーチ" },
  { brand_genre_id: 1, name: "フェンディ" },
  { brand_genre_id: 1, name: "メゾンキツネ" },
  { brand_genre_id: 1, name: "メゾンフルール" },
  { brand_genre_id: 1, name: "ヴゼット" },
  { brand_genre_id: 1, name: "Y3" },
  { brand_genre_id: 1, name: "ロキト" },
  { brand_genre_id: 1, name: "ブラックバイマウジー" },
  { brand_genre_id: 1, name: "ピンキー＆ダイアン" },
  { brand_genre_id: 1, name: "ナラカミーチェ" },
  { brand_genre_id: 1, name: "セタイチロウ" },
  { brand_genre_id: 1, name: "aquagirl" },
  { brand_genre_id: 1, name: "メンズビギ" },
  { brand_genre_id: 1, name: "ガラージュ" },
  { brand_genre_id: 1, name: "ポロ ラルフ ローレン" },
  { brand_genre_id: 1, name: "ランバン" },
  { brand_genre_id: 1, name: "オロビアンコ" },
  { brand_genre_id: 1, name: "ケープハイツ" },
  { brand_genre_id: 2, name: "ビームス" },
  { brand_genre_id: 2, name: "RALPHLAUREN" },
  { brand_genre_id: 2, name: "UNITED ALLOWS" },
  { brand_genre_id: 2, name: "ARMANI" },
  { brand_genre_id: 2, name: "DIESEL" },
  { brand_genre_id: 2, name: "しまむら" },
  { brand_genre_id: 2, name: "ZARA" },
  { brand_genre_id: 2, name: "H&M" },
  { brand_genre_id: 2, name: "GAP" },
  { brand_genre_id: 2, name: "GU" },
  { brand_genre_id: 2, name: "SHIPS KIDS" },
  { brand_genre_id: 2, name: "フィス" },
  { brand_genre_id: 2, name: "プチバトー" },
  { brand_genre_id: 2, name: "パンパンチュチュ" },
  { brand_genre_id: 2, name: "ボボショセス" },
  { brand_genre_id: 2, name: "ボンポワン" },
  { brand_genre_id: 2, name: "ミナペルホネン" },
  { brand_genre_id: 2, name: "ククゥマノン" },
  { brand_genre_id: 2, name: "ポロ ラルフ ローレン" },
  { brand_genre_id: 2, name: "ランバン" },
  { brand_genre_id: 3, name: "アルマーニジュニア" },
  { brand_genre_id: 3, name: "ラルフローレン ベビー" },
  { brand_genre_id: 3, name: "ベビー ギャップ" },
  { brand_genre_id: 3, name: "フェンディ" },
  { brand_genre_id: 3, name: "メゾンキツネ" },
  { brand_genre_id: 3, name: "メゾンフルール" },
  { brand_genre_id: 3, name: "ヴゼット" },
  { brand_genre_id: 3, name: "Y3" },
  { brand_genre_id: 3, name: "ロキト" },
  { brand_genre_id: 3, name: "ブラックバイマウジー" },
  { brand_genre_id: 3, name: "ピンキー＆ダイアン" },
  { brand_genre_id: 3, name: "ナラカミーチェ" },
  { brand_genre_id: 3, name: "セタイチロウ" },
  { brand_genre_id: 3, name: "aquagirl" },
  { brand_genre_id: 3, name: "メンズビギ" },
  { brand_genre_id: 3, name: "ガラージュ" },
  { brand_genre_id: 3, name: "ポロ ラルフ ローレン" },
  { brand_genre_id: 3, name: "ランバン" },
  { brand_genre_id: 3, name: "オロビアンコ" },
  { brand_genre_id: 3, name: "ケープハイツ" },
  { brand_genre_id: 4, name: "IDÉE" },
  { brand_genre_id: 4, name: "TRUCK FURNITURE" },
  { brand_genre_id: 4, name: "Eames" },
  { brand_genre_id: 4, name: "Francfranc" },
  { brand_genre_id: 4, name: "STREAMLINE SOFA" },
  { brand_genre_id: 4, name: "CH24" },
  { brand_genre_id: 4, name: "arflex" },
  { brand_genre_id: 4, name: "HUKLA" },
  { brand_genre_id: 4, name: "H.W.F" },
  { brand_genre_id: 4, name: "LENSVELT" },
  { brand_genre_id: 4, name: "HIRASHIMA(" },
  { brand_genre_id: 4, name: "MASTERWAL" },
  { brand_genre_id: 4, name: "カリモク家具" },
  { brand_genre_id: 4, name: "柏木工" },
  { brand_genre_id: 4, name: "maruni" },
  { brand_genre_id: 4, name: "string" },
  { brand_genre_id: 4, name: "PACIFIC FURNITURE SERVICE" },
  { brand_genre_id: 4, name: "ACME FURNITURE" },
  { brand_genre_id: 4, name: "METROCS" },
  { brand_genre_id: 4, name: "広松木工" },
  ])

81.upto(100) do |i|
  Brand.create( name: "キッチン・食器#{i}", brand_genre_id: 5)
end
101.upto(120) do |i|
  Brand.create( name: "時計#{i}", brand_genre_id: 6)
end

Brand.create([
  { brand_genre_id: 7, name: "エルメス" },
  { brand_genre_id: 7, name: "シャネル" },
  { brand_genre_id: 7, name: "ジルスチュアート" },
  { brand_genre_id: 7, name: "ブルガリ" },
  { brand_genre_id: 7, name: "資生堂" },
  { brand_genre_id: 7, name: "アナスイコスメティックス" },
  { brand_genre_id: 7, name: "カネボウ" },
  { brand_genre_id: 7, name: "ディオール" },
  { brand_genre_id: 7, name: "ドクターシーラボ" },
  { brand_genre_id: 7, name: "ティファニー" },
  { brand_genre_id: 7, name: "サルヴァトーレ　フェラガモ" },
  { brand_genre_id: 7, name: "エスティローダー" },
  { brand_genre_id: 7, name: "ヴェルサーチ" },
  { brand_genre_id: 7, name: "クリスチャンルブタン" },
  { brand_genre_id: 7, name: "グッチ" },
  { brand_genre_id: 7, name: "クロエ" },
  { brand_genre_id: 7, name: "コーチ" },
  { brand_genre_id: 7, name: "ジバンシイ" },
  { brand_genre_id: 7, name: "ニナリッチ" },
  { brand_genre_id: 7, name: "バーバリー" },

  { brand_genre_id: 8, name: "プレイステーション4" },
  { brand_genre_id: 8, name: "Xbox One" },
  { brand_genre_id: 8, name: "ニンテンドースイッチ" },
  { brand_genre_id: 8, name: "ファミコン" },
  { brand_genre_id: 8, name: "スーパーファミコン" },
  { brand_genre_id: 8, name: "ゲームボーイ" },
  { brand_genre_id: 8, name: "ウィー" },
  { brand_genre_id: 8, name: "ウィーユー" },
  { brand_genre_id: 8, name: "ゲームキューブ" },
  { brand_genre_id: 8, name: "Xbox360" },
  { brand_genre_id: 8, name: "Xbox" },
  { brand_genre_id: 8, name: "ニンテンドー3DS" },
  { brand_genre_id: 8, name: "プレイステーションヴィータ" },
  { brand_genre_id: 8, name: "ニンテンドー64" },
  { brand_genre_id: 8, name: "メガドライブ" },
  { brand_genre_id: 8, name: "PCエンジン" },
  { brand_genre_id: 8, name: "ゲームキューブ" },
  { brand_genre_id: 8, name: "プレイステーションポータブル" },
  { brand_genre_id: 8, name: "セガサターン" },
  { brand_genre_id: 8, name: "ドリームキャスト" },
  ])

161.upto(180) do |i|
  Brand.create( name: "スポーツ・レジャー#{i}", brand_genre_id: 9)
end
181.upto(200) do |i|
  Brand.create( name: "スマートフォン#{i}", brand_genre_id: 10)
end
201.upto(220) do |i|
  Brand.create( name: "バイク#{i}", brand_genre_id: 11)
end
Brand.create([
  { brand_genre_id: 12, name: "ヤマハ" },
  { brand_genre_id: 12, name: "ESP" },
  { brand_genre_id: 12, name: "フェンダー" },
  { brand_genre_id: 12, name: "フェルナンデス" },
  { brand_genre_id: 12, name: "ギブソン" },
  { brand_genre_id: 12, name: "キョーリツ" },
  { brand_genre_id: 12, name: "TAMA" },
  { brand_genre_id: 12, name: "スペクター" },
  { brand_genre_id: 12, name: "BOSS" },
  { brand_genre_id: 12, name: "SUZUKI" },
  { brand_genre_id: 12, name: "REON" },
  { brand_genre_id: 12, name: "TOMBO" },
  { brand_genre_id: 12, name: "ビクター" },
  { brand_genre_id: 12, name: "unknown" },
  { brand_genre_id: 12, name: "TOKAI" },
  { brand_genre_id: 12, name: "Combat" },
  { brand_genre_id: 12, name: "Moon" },
  { brand_genre_id: 12, name: "Seed" },
  { brand_genre_id: 12, name: "3M" },
  { brand_genre_id: 12, name: "buzz" },
  ])

241.upto(260) do |i|
  Brand.create( name: "自動車#{i}", brand_genre_id: 13)
end
261.upto(280) do |i|
  Brand.create( name: "食品#{i}", brand_genre_id: 14)
end


user = User.new(nickname: "admin", email: "admin@admin", password: "password")
user.save!

user = User.new(nickname: "hoge", email: "hoge@hoge", password: "hogehoge")
user.save!

(3..10).each do |i|
  user = User.new(nickname: "高知#{i}かつお", email: "hoge#{i}@com", password: "hogehoge")
  user.save!
end


(1..10).each do |i|
  Address.create(
    user_id: i,
    name01: "高知#{i}",
    name02: "土佐#{i}郎",
    name03: "こうち#{i}",
    name04: "とさ#{i}ろう",
    zip: "777-7777",
    state: "高知県",
    city: "高知市",
    address_line: "1-1-1",
    tel: "000-0000-000#{i}",
  )
end

(1..10).each do |i|
  Creditcard.create(
    user_id: i,
    card_number: "****-****-****-7777",
    expiration_month: "04",
    expiration_year: "2018",
    security_code: "777",
  )
end


(1..50).each do |i|
  if (i % 10) == 0
    Item.create(
      name: "ルイヴィトン長財布#{i}",
      image: File.open("./app/assets/images/010.jpg"),
      text: "商品説明#{i}",
      brand_genre_id: 1,
      brand_id: 1,
      category_genre_id: 1,
      category_id: 1,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 1192,sale_status: 1,
      user_id: 3,
      )
  elsif (i % 9) == 0
    Item.create(
      name: "ps4#{i}",
      image: File.open("./app/assets/images/09.jpg"),
      text: "商品説明#{i}",
      brand_genre_id: 2,
      brand_id: 21,
      category_genre_id: 2,
      category_id: 21,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 1192,sale_status: 0,
      user_id: 4,
      )
  elsif (i % 8) == 0
    Item.create(
      name: "パンダ#{i}",
      image: File.open("./app/assets/images/8.jpg"),
      text: "商品説明#{i}",
      brand_genre_id: 3,
      brand_id: 41,
      category_genre_id: 3,
      category_id: 41,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 1192,sale_status: 2,
      user_id: 5,
      )
  elsif (i % 7) == 0
    Item.create(
      name: "シャネルバッグ#{i}",
      image: File.open("./app/assets/images/07.jpg"),
      text: "商品説明#{i}",
      brand_genre_id: 4,
      brand_id: 61,
      category_genre_id: 4,
      category_id: 61,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 1192,sale_status: 0,
      user_id: 3,
      )
  elsif (i % 6) == 0
    Item.create(
      name: "NIKEナイキランニングパンツ#{i}",
      image: File.open("./app/assets/images/06.jpg"),
      text: "商品説明#{i}",
      brand_genre_id: 5,
      brand_id: 81,
      category_genre_id: 5,
      category_id: 81,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 1192,sale_status: 0,
      user_id: 4,
      )
  elsif (i % 5) == 0
    Item.create(
      name: "NIKE靴スニーカー#{i}",
      image: File.open("./app/assets/images/05.jpg"),
      text: "商品説明#{i}",
      brand_genre_id: 1,
      brand_id: 2,
      category_genre_id: 1,
      category_id: 2,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 1192,sale_status: 0,
      user_id: 5,
      )
  elsif (i % 4) == 0
    Item.create(
      name: "supremeシュプリームキャップぼうし#{i}",
      image: File.open("./app/assets/images/04.jpg"),
      text: "商品説明#{i}",
      brand_genre_id: 2,
      brand_id: 22,
      category_genre_id: 2,
      category_id: 22,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 1192,sale_status: 0,
      user_id: 3,
      )
  elsif (i % 3) == 0
    Item.create(
      name: "CHANELシャネル香水#{i}",
      image: File.open("./app/assets/images/03.jpg"),
      text: "商品説明#{i}",
      brand_genre_id: 3,
      brand_id: 42,
      category_genre_id: 3,
      category_id: 42,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 1192,sale_status: 0,
      user_id: 4,
      )
  elsif (i % 2) == 0
    Item.create(
      name: "supremeシュプリームTシャツ#{i}",
      image: File.open("./app/assets/images/02.jpg"),
      text: "商品説明#{i}",
      brand_genre_id: 4,
      brand_id: 62,
      category_genre_id: 4,
      category_id: 62,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 1192,sale_status: 0,
      user_id: 5,
      )
  else
    Item.create(
      name: "シャネル ボーダー ニット ツイード トップス",
      image: File.open("./app/assets/images/01.jpg"),
      text: "シャネルのボーダーニットです。サイズ38。カシミア100パーセントです。",
      brand_genre_id: 1,
      brand_id: 2,
      category_genre_id: 1,
      category_id: 1,
      quality_status: "目立った傷や汚れなし",
      days:"２〜３日で発送",
      price: 70300,sale_status: 0,
      user_id: 5,
      )
  end
end

Item.create(
      name: "ビームス トップス",
      image: File.open("./app/assets/images/002021001.jpg"),
      text: "ビームス トップスビームス トップスビームス トップス",
      brand_genre_id: 2,
      brand_id: 21,
      category_genre_id: 2,
      category_id: 21,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 6900,
      sale_status: 0,
      user_id: 2,
      )
Item.create(
      name: "ビームス トップス",
      image: File.open("./app/assets/images/002021001.jpg"),
      text: "ビームス トップスビームス トップスビームス トップス",
      brand_genre_id: 2,
      brand_id: 21,
      category_genre_id: 2,
      category_id: 21,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 6900,
      sale_status: 0,
      user_id: 2,
      )
Item.create(
      name: "ビームス トップス",
      image: File.open("./app/assets/images/002021002.jpg"),
      text: "ビームス トップスビームス トップスビームス トップス",
      brand_genre_id: 2,
      brand_id: 21,
      category_genre_id: 2,
      category_id: 21,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 5900,
      sale_status: 0,
      user_id: 3,
      )
Item.create(
      name: "RALPHLAUREN トップス",
      image: File.open("./app/assets/images/002021003.jpg"),
      text: "RALPHLAUREN トップスRALPHLAUREN トップスRALPHLAUREN トップス",
      brand_genre_id: 2,
      brand_id: 22,
      category_genre_id: 2,
      category_id: 21,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 7900,
      sale_status: 0,
      user_id: 4,
      )
Item.create(
      name: "RALPHLAUREN トップス",
      image: File.open("./app/assets/images/002021004.jpg"),
      text: "RALPHLAUREN トップスRALPHLAUREN トップスRALPHLAUREN トップス",
      brand_genre_id: 2,
      brand_id: 22,
      category_genre_id: 2,
      category_id: 21,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 7900,
      sale_status: 0,
      user_id: 5,
      )
Item.create(
      name: "UNITED ALLOWS ジャケット/アウター",
      image: File.open("./app/assets/images/002022001.jpg"),
      text: "UNITED ALLOWS ジャケット/アウターUNITED ALLOWS ジャケット/アウターUNITED ALLOWS ジャケット/アウター",
      brand_genre_id: 2,
      brand_id: 23,
      category_genre_id: 2,
      category_id: 22,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 27900,
      sale_status: 0,
      user_id: 6,
      )
Item.create(
      name: "UNITED ALLOWS ジャケット/アウター",
      image: File.open("./app/assets/images/002022002.jpg"),
      text: "UNITED ALLOWS ジャケット/アウターUNITED ALLOWS ジャケット/アウターUNITED ALLOWS ジャケット/アウター",
      brand_genre_id: 2,
      brand_id: 23,
      category_genre_id: 2,
      category_id: 22,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 27900,
      sale_status: 0,
      user_id: 7,
      )
Item.create(
      name: "ARMANI ジャケット/アウター",
      image: File.open("./app/assets/images/002022003.jpg"),
      text: "ARMANI ジャケット/アウターARMANI ジャケット/アウターARMANI ジャケット/アウター",
      brand_genre_id: 2,
      brand_id: 24,
      category_genre_id: 2,
      category_id: 22,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 107900,
      sale_status: 0,
      user_id: 8,
      )
Item.create(
      name: "ARMANI ジャケット/アウター",
      image: File.open("./app/assets/images/002022004.jpg"),
      text: "ARMANI ジャケット/アウターARMANI ジャケット/アウターARMANI ジャケット/アウター",
      brand_genre_id: 2,
      brand_id: 24,
      category_genre_id: 2,
      category_id: 22,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 87900,
      sale_status: 0,
      user_id: 9,
      )
Item.create(
      name: "DIESEL パンツ",
      image: File.open("./app/assets/images/002023001.jpg"),
      text: "DIESEL パンツDIESEL パンツDIESEL パンツ",
      brand_genre_id: 2,
      brand_id: 25,
      category_genre_id: 2,
      category_id: 23,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 37900,
      sale_status: 0,
      user_id: 10,
      )
Item.create(
      name: "DIESEL パンツ",
      image: File.open("./app/assets/images/002023002.jpg"),
      text: "DIESEL パンツDIESEL パンツDIESEL パンツ",
      brand_genre_id: 2,
      brand_id: 25,
      category_genre_id: 2,
      category_id: 23,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 37900,
      sale_status: 0,
      user_id: 2,
      )
Item.create(
      name: "DIESEL パンツ",
      image: File.open("./app/assets/images/002023003.jpg"),
      text: "DIESEL パンツDIESEL パンツDIESEL パンツ",
      brand_genre_id: 2,
      brand_id: 25,
      category_genre_id: 2,
      category_id: 23,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 37900,
      sale_status: 0,
      user_id: 3,
      )
Item.create(
      name: "DIESEL パンツ",
      image: File.open("./app/assets/images/002023004.jpg"),
      text: "DIESEL パンツDIESEL パンツDIESEL パンツ",
      brand_genre_id: 2,
      brand_id: 25,
      category_genre_id: 2,
      category_id: 23,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 37900,
      sale_status: 0,
      user_id: 4,
      )
Item.create(
      name: "キッズ靴 アルマーニジュニア",
      image: File.open("./app/assets/images/003031001.jpg"),
      text: "キッズ靴 アルマーニキッズ靴 アルマーニキッズ靴 アルマーニ",
      brand_genre_id: 3,
      brand_id: 41,
      category_genre_id: 3,
      category_id: 41,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 6900,
      sale_status: 0,
      user_id: 5,
      )
Item.create(
      name: "キッズ靴 アルマーニジュニア",
      image: File.open("./app/assets/images/003031002.jpg"),
      text: "キッズ靴 アルマーニキッズ靴 アルマーニキッズ靴 アルマーニ",
      brand_genre_id: 3,
      brand_id: 41,
      category_genre_id: 3,
      category_id: 41,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 6900,
      sale_status: 0,
      user_id: 6,
      )
Item.create(
      name: "キッズ靴 アルマーニジュニア",
      image: File.open("./app/assets/images/003031003.jpg"),
      text: "キッズ靴 アルマーニキッズ靴 アルマーニキッズ靴 アルマーニ",
      brand_genre_id: 3,
      brand_id: 41,
      category_genre_id: 3,
      category_id: 41,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 4900,
      sale_status: 0,
      user_id: 7,
      )
Item.create(
      name: "キッズ靴 アルマーニジュニア",
      image: File.open("./app/assets/images/003031004.jpg"),
      text: "キッズ靴 アルマーニキッズ靴 アルマーニキッズ靴 アルマーニ",
      brand_genre_id: 3,
      brand_id: 41,
      category_genre_id: 3,
      category_id: 41,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 5900,
      sale_status: 0,
      user_id: 8,
      )
Item.create(
      name: "ベビー服 女の子用 ラルフローレン ベビー",
      image: File.open("./app/assets/images/003032001.jpg"),
      text: "ベビー服 女の子用 ラルフローレン ベビーベビー服 女の子用 ラルフローレン ベビーベビー服 女の子用 ラルフローレン ベビー",
      brand_genre_id: 3,
      brand_id: 42,
      category_genre_id: 3,
      category_id: 42,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 5900,
      sale_status: 0,
      user_id: 9,
      )
Item.create(
      name: "ベビー服 女の子用 ラルフローレン ベビー",
      image: File.open("./app/assets/images/003032002.jpg"),
      text: "ベビー服 女の子用 ラルフローレン ベビーベビー服 女の子用 ラルフローレン ベビーベビー服 女の子用 ラルフローレン ベビー",
      brand_genre_id: 3,
      brand_id: 42,
      category_genre_id: 3,
      category_id: 42,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 4900,
      sale_status: 0,
      user_id: 10,
      )
Item.create(
      name: "ベビー服 女の子用 ラルフローレン ベビー",
      image: File.open("./app/assets/images/003032003.jpg"),
      text: "ベビー服 女の子用 ラルフローレン ベビーベビー服 女の子用 ラルフローレン ベビーベビー服 女の子用 ラルフローレン ベビー",
      brand_genre_id: 3,
      brand_id: 42,
      category_genre_id: 3,
      category_id: 42,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 6900,
      sale_status: 0,
      user_id: 2,
      )
Item.create(
      name: "ベビー服 女の子用 ラルフローレン ベビー",
      image: File.open("./app/assets/images/003032004.jpg"),
      text: "ベビー服 女の子用 ラルフローレン ベビーベビー服 女の子用 ラルフローレン ベビーベビー服 女の子用 ラルフローレン ベビー",
      brand_genre_id: 3,
      brand_id: 42,
      category_genre_id: 3,
      category_id: 42,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 7900,
      sale_status: 0,
      user_id: 3,
      )
Item.create(
      name: "ベビー服 男の子用 ベビー ギャップ",
      image: File.open("./app/assets/images/003033001.jpg"),
      text: "ベビー服 男の子用 ベビー ギャップベビー服 男の子用 ベビー ギャップベビー服 男の子用 ベビー ギャップ",
      brand_genre_id: 3,
      brand_id: 43,
      category_genre_id: 3,
      category_id: 43,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 5900,
      sale_status: 0,
      user_id: 4,
      )
Item.create(
      name: "ベビー服 男の子用 ベビー ギャップ",
      image: File.open("./app/assets/images/003033002.jpg"),
      text: "ベビー服 男の子用 ベビー ギャップベビー服 男の子用 ベビー ギャップベビー服 男の子用 ベビー ギャップ",
      brand_genre_id: 3,
      brand_id: 43,
      category_genre_id: 3,
      category_id: 43,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 4900,
      sale_status: 0,
      user_id: 5,
      )
Item.create(
      name: "ベビー服 男の子用 ベビー ギャップ",
      image: File.open("./app/assets/images/003033003.jpg"),
      text: "ベビー服 男の子用 ベビー ギャップベビー服 男の子用 ベビー ギャップベビー服 男の子用 ベビー ギャップ",
      brand_genre_id: 3,
      brand_id: 43,
      category_genre_id: 3,
      category_id: 43,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 6900,
      sale_status: 0,
      user_id: 6,
      )
Item.create(
      name: "ベビー服 男の子用 ベビー ギャップ",
      image: File.open("./app/assets/images/003033004.jpg"),
      text: "ベビー服 男の子用 ベビー ギャップベビー服 男の子用 ベビー ギャップベビー服 男の子用 ベビー ギャップ",
      brand_genre_id: 3,
      brand_id: 43,
      category_genre_id: 3,
      category_id: 43,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 6900,
      sale_status: 0,
      user_id: 7,
      )
Item.create(
      name: "収納家具 IDÉE",
      image: File.open("./app/assets/images/004041001.jpg"),
      text: "収納家具 IDÉE収納家具 IDÉE収納家具 IDÉE",
      brand_genre_id: 4,
      brand_id: 61,
      category_genre_id: 4,
      category_id: 61,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 26900,
      sale_status: 0,
      user_id: 8,
      )
Item.create(
      name: "収納家具 IDÉE",
      image: File.open("./app/assets/images/004041002.jpg"),
      text: "収納家具 IDÉE収納家具 IDÉE収納家具 IDÉE",
      brand_genre_id: 4,
      brand_id: 61,
      category_genre_id: 4,
      category_id: 61,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 36900,
      sale_status: 0,
      user_id: 9,
      )
Item.create(
      name: "収納家具 TRUCK FURNITURE",
      image: File.open("./app/assets/images/004041003.jpg"),
      text: "収納家具 TRUCK FURNITURE収納家具 TRUCK FURNITURE収納家具 TRUCK FURNITURE",
      brand_genre_id: 4,
      brand_id: 62,
      category_genre_id: 4,
      category_id: 61,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 24800,
      sale_status: 0,
      user_id: 2,
      )
Item.create(
      name: "収納家具 TRUCK FURNITURE",
      image: File.open("./app/assets/images/004041004.jpg"),
      text: "収納家具 TRUCK FURNITURE収納家具 TRUCK FURNITURE収納家具 TRUCK FURNITURE",
      brand_genre_id: 4,
      brand_id: 62,
      category_genre_id: 4,
      category_id: 61,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 34800,
      sale_status: 0,
      user_id: 3,
      )
Item.create(
      name: "椅子/チェア Eames",
      image: File.open("./app/assets/images/004042001.jpg"),
      text: "椅子/チェア Eames椅子/チェア Eames椅子/チェア Eames",
      brand_genre_id: 4,
      brand_id: 63,
      category_genre_id: 4,
      category_id: 62,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 4800,
      sale_status: 0,
      user_id: 4,
      )
Item.create(
      name: "椅子/チェア Eames",
      image: File.open("./app/assets/images/004042002.jpg"),
      text: "椅子/チェア Eames椅子/チェア Eames椅子/チェア Eames",
      brand_genre_id: 4,
      brand_id: 63,
      category_genre_id: 4,
      category_id: 62,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 5800,
      sale_status: 0,
      user_id: 5,
      )
Item.create(
      name: "椅子/チェア Eames",
      image: File.open("./app/assets/images/004042003.jpg"),
      text: "椅子/チェア Eames椅子/チェア Eames椅子/チェア Eames",
      brand_genre_id: 4,
      brand_id: 63,
      category_genre_id: 4,
      category_id: 62,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 6800,
      sale_status: 0,
      user_id: 6,
      )
Item.create(
      name: "椅子/チェア Eames",
      image: File.open("./app/assets/images/004042004.jpg"),
      text: "椅子/チェア Eames椅子/チェア Eames椅子/チェア Eames",
      brand_genre_id: 4,
      brand_id: 63,
      category_genre_id: 4,
      category_id: 62,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 108000,
      sale_status: 0,
      user_id: 7,
      )
Item.create(
      name: "ソファ Francfranc",
      image: File.open("./app/assets/images/004043001.jpg"),
      text: "ソファ Francfrancソファ Francfrancソファ Francfranc",
      brand_genre_id: 4,
      brand_id: 64,
      category_genre_id: 4,
      category_id: 63,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 65800,
      sale_status: 0,
      user_id: 8,
      )
Item.create(
      name: "ソファ Francfranc",
      image: File.open("./app/assets/images/004043002.jpg"),
      text: "ソファ Francfrancソファ Francfrancソファ Francfranc",
      brand_genre_id: 4,
      brand_id: 64,
      category_genre_id: 4,
      category_id: 63,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 44800,
      sale_status: 0,
      user_id: 9,
      )
Item.create(
      name: "ソファ Francfranc",
      image: File.open("./app/assets/images/004043003.jpg"),
      text: "ソファ Francfrancソファ Francfrancソファ Francfranc",
      brand_genre_id: 4,
      brand_id: 64,
      category_genre_id: 4,
      category_id: 63,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 35800,
      sale_status: 0,
      user_id: 10,
      )
Item.create(
      name: "ソファ Francfranc",
      image: File.open("./app/assets/images/004043004.jpg"),
      text: "ソファ Francfrancソファ Francfrancソファ Francfranc",
      brand_genre_id: 4,
      brand_id: 64,
      category_genre_id: 4,
      category_id: 63,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 36800,
      sale_status: 0,
      user_id: 2,
      )

Item.create(
      name: "プレイステーション4 Pro ジェット・ブラック 1TB (CUH-7000BB01)",
      image: File.open("./app/assets/images/005082001.jpg"),
      text: "プレステ4。フルHDテレビをお持ちなら、PS4 ProがPS4のすべてのゲームを1080pに最適化して出力",
      brand_genre_id: 8,
      brand_id: 141,
      category_genre_id: 5,
      category_id: 83,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 33000,sale_status: 0,
      user_id: 5,
)
Item.create(
      name: "プレイステーション4 グランツーリスモSPORT リミテッドエディション [ゲーム機本体]",
      image: File.open("./app/assets/images/005082002.jpg"),
      text: "PlayStation 4 (プレイステーション4) グランツーリスモSPORT リミテッドエディション [ゲーム機本体]",
      brand_genre_id: 8,
      brand_id: 141,
      category_genre_id: 5,
      category_id: 83,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 45000,sale_status: 0,
      user_id: 5,
)
Item.create(
      name: "Nintendo Switch 本体 (ニンテンドースイッチ) 【Joy-Con (L) / (R) グレー】",
      image: File.open("./app/assets/images/005082003.jpg"),
      text: "Nintendo Switch 本体 (ニンテンドースイッチ) 【Joy-Con (L) / (R) グレー】",
      brand_genre_id: 8,
      brand_id: 143,
      category_genre_id: 5,
      category_id: 83,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 35000,sale_status: 0,
      user_id: 9,
)
Item.create(
      name: "Nintendo ニンテンドークラシックミニ スーパーファミコン",
      image: File.open("./app/assets/images/005082004.jpg"),
      text: " Nintendo ニンテンドークラシックミニ スーパーファミコン",
      brand_genre_id: 8,
      brand_id: 145,
      category_genre_id: 5,
      category_id: 83,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 8000,sale_status: 0,
      user_id: 9,
)
Item.create(
      name: "Nintendo ニンテンドークラシックミニ ファミリーコンピュータ",
      image: File.open("./app/assets/images/005082005.jpg"),
      text: "Nintendo ニンテンドークラシックミニ ファミリーコンピュータ",
      brand_genre_id: 8,
      brand_id: 144,
      category_genre_id: 5,
      category_id: 83,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 6500,sale_status: 0,
      user_id: 7,
)
Item.create(
      name: "Nintendo Newニンテンドー3DS LL パールホワイト",
      image: File.open("./app/assets/images/005082006.jpg"),
      text: "Nintendo  Newニンテンドー3DS LL パールホワイト",
      brand_genre_id: 8,
      brand_id: 152,
      category_genre_id: 5,
      category_id: 83,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 20500,sale_status: 0,
      user_id: 7,
)
Item.create(
      name: "Nintendo Newニンテンドー3DS LL メタリックブルー",
      image: File.open("./app/assets/images/005082007.jpg"),
      text: "Nintendo Newニンテンドー3DS LL メタリックブルー",
      brand_genre_id: 8,
      brand_id: 152,
      category_genre_id: 5,
      category_id: 83,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 10500,sale_status: 0,
      user_id: 7,
)
Item.create(
      name: "Xbox One X Forza Horizon 4/Forza Motorsport 7 同梱版",
      image: File.open("./app/assets/images/005082008.jpg"),
      text: "Xbox One X Forza Horizon 4/Forza Motorsport 7 同梱版",
      brand_genre_id: 8,
      brand_id: 142,
      category_genre_id: 5,
      category_id: 83,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 55500,sale_status: 0,
      user_id: 10,
)
Item.create(
      name: "Xbox One Elite ワイヤレスコントローラー (ホワイト スペシャル エディション)",
      image: File.open("./app/assets/images/005082009.jpg"),
      text: "Xbox One Elite ワイヤレスコントローラー (ホワイト スペシャル エディション)",
      brand_genre_id: 8,
      brand_id: 142,
      category_genre_id: 5,
      category_id: 83,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 20500,sale_status: 0,
      user_id: 10,
)
Item.create(
      name: "Xbox One S 500GB Ultra HD ブルーレイ対応プレイヤー Minecraft 同梱版",
      image: File.open("./app/assets/images/005082010.jpg"),
      text: "Xbox One S 500GB Ultra HD ブルーレイ対応プレイヤー Minecraft 同梱版",
      brand_genre_id: 8,
      brand_id: 142,
      category_genre_id: 5,
      category_id: 83,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 29800,sale_status: 0,
      user_id: 10,
)
Item.create(
      name: "Xbox One S 1TB Ultra HDブルーレイ対応プレイヤー Forza Horizon 3 同梱版 ",
      image: File.open("./app/assets/images/005082011.jpg"),
      text: "Xbox One S 1TB Ultra HDブルーレイ対応プレイヤー Forza Horizon 3 同梱版 ",
      brand_genre_id: 8,
      brand_id: 142,
      category_genre_id: 5,
      category_id: 83,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 35800,sale_status: 0,
      user_id: 4,
)
Item.create(
      name: "Xbox One X シャドウ オブ ザ トゥームレイダー 同梱版 (CYV-00111)",
      image: File.open("./app/assets/images/005082012.jpg"),
      text: "Xbox One X シャドウ オブ ザ トゥームレイダー 同梱版 (CYV-00111)",
      brand_genre_id: 8,
      brand_id: 142,
      category_genre_id: 5,
      category_id: 83,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 55200,sale_status: 0,
      user_id: 3,
)

Item.create(
      name: "YAMAHA S90XS【超希少！生産完了品・箱ボロアウトレット超特価！】",
      image: File.open("./app/assets/images/006106001.jpg"),
      text: "生産完了後も高い人気を誇り、プロからも高い評価を得ている88鍵盤ピアノタッチシンセ「YAMAHA S90XS」の箱ボロアウトレット品が完全台数限定超特価",
      brand_genre_id: 12,
      brand_id: 221,
      category_genre_id: 6,
      category_id: 106,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 180000,sale_status: 0,
      user_id: 5,
)
Item.create(
      name: "YAMAHA MODX8【88鍵盤】【入門セット】【kbdset】",
      image: File.open("./app/assets/images/006106002.jpg"),
      text: "フラッグシップモデル「MONTAGE」直系の軽量ピアノタッチシンセ「YAMAHA MODX8」が登場！",
      brand_genre_id: 12,
      brand_id: 221,
      category_genre_id: 6,
      category_id: 106,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 180000,sale_status: 0,
      user_id: 9,
)
Item.create(
      name: "ヤマハ　ブラック・P-515B対応スタンド",
      image: File.open("./app/assets/images/006106003.jpg"),
      text: "YAMAHA L-515B 【ブラック・P-515B対応スタンド】",
      brand_genre_id: 12,
      brand_id: 221,
      category_genre_id: 6,
      category_id: 106,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 15000,sale_status: 0,
      user_id: 9,
)
Item.create(
      name: "スペクター　SPECTOR Euro 5 LX (Ultra Amber)",
      image: File.open("./app/assets/images/006106004.jpg"),
      text: "こちらは通常使用されるトップ材のグレードをより高めた非常に動きのある杢が選定されております。",
      brand_genre_id: 12,
      brand_id: 228,
      category_genre_id: 6,
      category_id: 106,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 280000,sale_status: 0,
      user_id: 9,
)
Item.create(
      name: "フェルナンデス　FERNANDES MB-CUSTOM SEELA【D’ERLANGER, SEELA MODEL】",
      image: File.open("./app/assets/images/006106005.jpg"),
      text: "デランジェ再結成10周年のタイミングにて発売された、SEELA(シーラ)氏の本人仕様のモデル！！ファンなら思わず頷いてしまう、プレイヤーならではの目線も見逃せないところ。",
      brand_genre_id: 12,
      brand_id: 224,
      category_genre_id: 6,
      category_id: 106,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 380000,sale_status: 0,
      user_id: 4,
)
Item.create(
      name: "フェルナンデス　FERNANDES RE-480 IS【D’ERLANGER,CIPHER MODEL】",
      image: File.open("./app/assets/images/006106006.jpg"),
      text: "デランジェ再結成10周年のタイミングにて発売された、鮮烈なパープルラメフレーク、シャープなヘッドデザインが存在感抜群にて多くのファンを持つCIPHER氏のモデル。",
      brand_genre_id: 12,
      brand_id: 224,
      category_genre_id: 6,
      category_id: 106,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 480000,sale_status: 0,
      user_id: 4,
)
Item.create(
      name: "フェンダー　Fender MEX Player Jaguar Bass (Tidepool/Maple) [Made In Mexico] 【FENDER THE AUTUMN-WINTER 2018 CAMPAIGN】",
      image: File.open("./app/assets/images/006106007.jpg"),
      text: "フェンダー　Fender MEX Player Jaguar Bass (Tidepool/Maple) [Made In Mexico] 【FENDER THE AUTUMN-WINTER 2018 CAMPAIGN】",
      brand_genre_id: 12,
      brand_id: 223,
      category_genre_id: 6,
      category_id: 106,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 50000,sale_status: 0,
      user_id: 6,
)
Item.create(
      name: "ギブソン　Gibson Thunderbird Bass 2019 (Heritage Cherry Sunburst)",
      image: File.open("./app/assets/images/006106008.jpg"),
      text: "ギブソン　Gibson Thunderbird Bass 2019 (Heritage Cherry Sunburst)",
      brand_genre_id: 12,
      brand_id: 225,
      category_genre_id: 6,
      category_id: 106,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 198000,sale_status: 0,
      user_id: 6,
)
Item.create(
      name: "フェルナンデス　FERNANDES GUSTAVE ”BUCK-TICK 30th Anniversary Model” [BUCK-TICK”今井寿”シグネイチャーモデル]",
      image: File.open("./app/assets/images/006106009.jpg"),
      text: "BUCK-TICK 30周年記念モデル！！今井寿氏シグネイチャーモデルの集大成「GUSTAVE」待望の発売開始！",
      brand_genre_id: 12,
      brand_id: 224,
      category_genre_id: 6,
      category_id: 106,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 778000,sale_status: 0,
      user_id: 10,
)
Item.create(
      name: "フェルナンデス　TXL-HH Custom ”BUCK-TICK 30th Anniversary Model” (SWH) [BUCK-TICK”星野英彦”シグネイチャーモデル]",
      image: File.open("./app/assets/images/006106010.jpg"),
      text: "BUCK-TICK 30周年記念モデル！！星野英彦氏シグネイチャーモデル「TXL-HH Custom」待望の発売開始！",
      brand_genre_id: 12,
      brand_id: 224,
      category_genre_id: 6,
      category_id: 106,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 518000,sale_status: 0,
      user_id: 10,
)
Item.create(
      name: "フェンダー　Custom Shop MBS 1962 Jazzmaster Relic 3-Tone Sunburst Master Built By Dennis Galuszka S/N R94470 【FENDER CUSTOM SHOP EXHIBITION選定品！】",
      image: File.open("./app/assets/images/006106011.jpg"),
      text: "フェンダー　Custom Shop MBS 1962 Jazzmaster Relic 3-Tone Sunburst Master Built By Dennis Galuszka S/N R94470 【FENDER CUSTOM SHOP EXHIBITION選定品！】",
      brand_genre_id: 12,
      brand_id: 223,
      category_genre_id: 6,
      category_id: 106,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 898000,sale_status: 0,
      user_id: 8,
)
Item.create(
      name: "ESP J-TVB-V -Maria-",
      image: File.open("./app/assets/images/006106012.jpg"),
      text: "本人直筆サイン入り認定書（シリアルナンバー入り）",
      brand_genre_id: 12,
      brand_id: 222,
      category_genre_id: 6,
      category_id: 106,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 498000,sale_status: 0,
      user_id: 8,
)

Item.create(
      name: "ツイリー ドゥ エルメス 香水",
      image: File.open("./app/assets/images/007124001.jpg"),
      text: "2017年8月29日発売のツイリー ドゥ エルメスです。",
      brand_genre_id: 7,
      brand_id: 121,
      category_genre_id: 7,
      category_id: 124,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 3000,sale_status: 0,
      user_id: 4,
)
Item.create(
      name: "シャネル ココ マドモアゼル オードゥパルファム アンタンス 香水",
      image: File.open("./app/assets/images/007124002.jpg"),
      text: "2018年発売の新作です。",
      brand_genre_id: 7,
      brand_id: 122,
      category_genre_id: 7,
      category_id: 124,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 5000,sale_status: 0,
      user_id: 7,
)
Item.create(
      name: "ブルガリ ローズ ゴルデア オードパルファム 香水",
      image: File.open("./app/assets/images/007124003.jpg"),
      text: "2018年発売の華やかなアニバーサリーエディションのボトルです。",
      brand_genre_id: 7,
      brand_id: 124,
      category_genre_id: 7,
      category_id: 124,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 30000,sale_status: 0,
      user_id: 8,
)
Item.create(
      name: "ブルガリ オムニア ピンク サファイヤ オードトワレ 香水",
      image: File.open("./app/assets/images/007124004.jpg"),
      text: "ピンクサファイアにインスパイアされたキュートな「オムニアピンクサファイヤ」が登場。ピンクポメロやピンクペッパー、ティアレフラワーなど、弾けるようなピンクカラーが放つエネルギーを感じる香り。",
      brand_genre_id: 7,
      brand_id: 124,
      category_genre_id: 7,
      category_id: 124,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 15000,sale_status: 0,
      user_id: 8,
)
Item.create(
      name: "シャネル　2018春夏コレクション ヴェルニ ロング トゥニュ　ネイルカラー",
      image: File.open("./app/assets/images/007123005.jpg"),
      text: "シャネル　LE VERNIS。2018年1月　パリのシャネル１店舗のみで先行発売。",
      brand_genre_id: 7,
      brand_id: 122,
      category_genre_id: 7,
      category_id: 123,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 10000,sale_status: 0,
      user_id: 4,
)
Item.create(
      name: "シャネル Rouge Allure INK アリュール 口紅",
      image: File.open("./app/assets/images/007122006.jpg"),
      text: "シャネル 2018秋 Rouge Allure Ink ルージュアリュールインク",
      brand_genre_id: 7,
      brand_id: 122,
      category_genre_id: 7,
      category_id: 122,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 10000,sale_status: 0,
      user_id: 4,
)
Item.create(
      name: "シャネル　2018年秋　ヴェルヴェット ヴェルニ 2本セット　ネイルカラー",
      image: File.open("./app/assets/images/007123007.jpg"),
      text: "シャネル　2018年秋　ヴェルヴェット ヴェルニ 2本セット　ネイルカラー",
      brand_genre_id: 7,
      brand_id: 122,
      category_genre_id: 7,
      category_id: 123,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 9999,sale_status: 0,
      user_id: 6,
)
Item.create(
      name: "シャネル　LE VERNIS＊2018年春夏コレクション新商品　ネイルカラー",
      image: File.open("./app/assets/images/007123008.jpg"),
      text: "シャネル　LE VERNIS＊2018年春夏コレクション新商品　ネイルカラー",
      brand_genre_id: 7,
      brand_id: 122,
      category_genre_id: 7,
      category_id: 123,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 6999,sale_status: 0,
      user_id: 6,
)
Item.create(
      name: "シャネル 2019年最新☆CHANEL ROUGE COCO GLOSS Trio Set☆グロスセット",
      image: File.open("./app/assets/images/007122009.jpg"),
      text: "シャネルの限定リップグロスセット、今年も２０１８年秋から新作が登場！",
      brand_genre_id: 7,
      brand_id: 122,
      category_genre_id: 7,
      category_id: 122,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 16000,sale_status: 0,
      user_id: 4,
)
Item.create(
      name: "シャネル 2019年最新☆CHANEL ROUGE COCO GLOSS Trio Set☆グロスセット",
      image: File.open("./app/assets/images/007122009.jpg"),
      text: "シャネルの限定リップグロスセット、今年も２０１８年秋から新作が登場！",
      brand_genre_id: 7,
      brand_id: 122,
      category_genre_id: 7,
      category_id: 122,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 16000,sale_status: 0,
      user_id: 4,
)
Item.create(
      name: "ジルスチュアート JILL STUART 香水",
      image: File.open("./app/assets/images/007124010.jpg"),
      text: "ジルバイ ジルスチュアート 30ml",
      brand_genre_id: 7,
      brand_id: 123,
      category_genre_id: 7,
      category_id: 124,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 7500,sale_status: 0,
      user_id: 4,
)
Item.create(
      name: "ジルスチュアート リラックス オード ホワイトフローラル 香水",
      image: File.open("./app/assets/images/007124011.jpg"),
      text: "ジルスチュアート リラックス オード ホワイトフローラル (オーデコロン) 50ml",
      brand_genre_id: 7,
      brand_id: 123,
      category_genre_id: 7,
      category_id: 124,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 3500,sale_status: 0,
      user_id: 4,
)
Item.create(
      name: "ジルスチュアート クリスタルブルーム　スノー 30ml 香水",
      image: File.open("./app/assets/images/007124012.jpg"),
      text: "ジルスチュアート クリスタルブルーム　スノーEDP SP 30ml",
      brand_genre_id: 7,
      brand_id: 123,
      category_genre_id: 7,
      category_id: 124,
      quality_status: "新品、未使用",
      days:"１〜２日で発送",
      price: 5500,sale_status: 0,
      user_id: 4,
)

Item.create(
  name: "シャネル シャネル ボーダー ニット ツイード トップス",
  image: File.open("./app/assets/images/01.jpg"),
  text: "シャネルのボーダーニットです。サイズ38。カシミア100パーセントです。",
  brand_genre_id: 1,
  brand_id: 2,
  category_genre_id: 1,
  category_id: 1,
  quality_status: "目立った傷や汚れなし",
  days:"２〜３日で発送",
  price: 70300,sale_status: 0,
  user_id: 5,
  )

Comment.create(
  text: "素敵なお品ですね。
おいくらまででしたらお値引きは可能でしょうか？
失礼なコメントをして申し訳ございません(>_<)",
  item_id: 1,
  user_id: 8,
)
Comment.create(
  text: "ありがとうございます。即決でしたら一万円のお値引きさせていただきます^_^
  ご検討よろしくお願いします。",
  item_id: 1,
  user_id: 5,
)
Comment.create(
  text: "ご返答ありがとうございます。
  また、お値引きの件もありがとうございます。
  確認させていただきたいのですが、着姿やロゴの画像を見せていただくことは可能でしょうか？",
  item_id: 1,
  user_id: 8,
)
Comment.create(
  text: "ご質問ありがとうございます。とりあえず着姿を撮影しました。よろしくお願いします。",
  item_id: 1,
  user_id: 5,
  comment_image: File.open("./app/assets/images/01_02.jpg")
)
Comment.create(
  text: "チャームポイントのロゴボタンです。よろしくお願いします。",
  item_id: 1,
  user_id: 5,
  comment_image: File.open("./app/assets/images/01_03.jpg")
)
Comment.create(
  text: "ご丁寧にありがとうございます。
購入を検討しておりますが、6万円にして頂くことは厳しいでしょうか？
大変不躾なお願いをして申し訳ございません(>_<)",
  item_id: 1,
  user_id: 8,
)
Comment.create(
  text: "こんにちは^_^まだ手元に置いておきたい気持ちと、悩みながら本日限りで6万円にさせていただきます。ご検討よろしくお願いします。",
  item_id: 1,
  user_id: 5,
)
Comment.create(
  text: "お値引きありがとうございます！さっそく購入させていただきました。よろしくお願いします！",
  item_id: 1,
  user_id: 8,
)